functionality:
  name: check_obsolete_terms
  namespace: common/ontology
  description: |
    Check for obsolete ontology terms in the dataset.
  argument_groups:
    - name: Inputs
      arguments:
        - name: "--input"
          type: file
          description: "Input h5ad file."
          required: true
          direction: input
          example: dataset.h5ad
        - name: "--struct"
          type: string
          description: "In which struct to look for the term."
          required: true
          direction: input
          example: "obs"
        - name: "--input_term"
          type: string
          description: "In which field to look for the term."
          required: true
          direction: input
          example: "cell_type_ontology_term_id"
    - name: Ontology
      arguments:
        - name: "--ontology"
          type: file
          description: "Ontology to check."
          required: true
          direction: input
          example: cl.obo
    - name: Arguments
      arguments:
        - name: "--obsolete_as_na"
          type: boolean
          description: "Whether to replace obsolete terms with NA."
          default: true  
    - name: Outputs
      arguments:
        - name: "--output"
          type: file
          description: Output h5ad file.
          direction: output
          example: output.h5ad
        - name: "--output_term"
          type: string
          description: "In which field to store the updated term."
          required: true
          example: "cell_type_ontology_term_id"
        - name: "--output_name"
          type: string
          description: "In which field to store the updated term name."
          required: true
          example: "cell_type"
        - name: "--output_obsolete"
          type: string
          description: "In which field to store whether a term is obsolete."
          required: true
          example: "cell_type_ontology_obsolete"
  resources:
    - type: r_script
      path: script.R
  test_resources:
    - type: r_script
      path: test.R
    - path: /resources_test/common/cellxgene_census
platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_r:1.0.2
    setup:
      - type: r
        packages: [ dplyr, tidyr, tibble, ontologyIndex, processx ]