# use method api spec
__merge__: ../../api/comp_method_embedding.yaml
functionality:
  name: scanorama_embed
  namespace: batch_integration/methods_embedding
  description: "Efficient integration of heterogeneous single-cell 
    transcriptomes using Scanorama"
  info:
    type: method
    method_name: Scanorama
    paper_reference: "hie2019efficient"
    code_url: https://github.com/brianhie/scanorama
    v1_url: openproblems/tasks/_batch_integration/batch_integration_graph/methods/scanorama.py
    v1_commit: 29803b95c88b4ec5921df2eec7111fd5d1a95daf
    preferred_normalization: log_cpm
    variants:
      scanorama_embed_full_unscaled:
      scanorama_embed_hvg_unscaled:
        hvg: true
      scanorama_embed_hvg_scaled:
        hvg: true
        preferred_normalization: log_cpm_scaled
      scanorama_embed_full_scaled:
        preferred_normalization: log_cpm_scaled
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: mumichae/scib-base:1.0.2
    setup:
      - type: python
        pypi:
          - scanorama
          - pyyaml
  - type: nextflow
