functionality:
  name: "log_scran_pooling"
  namespace: "label_projection/data_processing/normalize/scran"
  version: "dev"
  description: "Normalize data"
  authors:
    - name: "Scott Gigante"
      roles: [ author ]
      props: { github: scottgigante }
    - name: "Vinicius Chagas"
      roles: [ maintainer ]
      props: { github: chagasVinicius }
  arguments:
    - name: "--input"
      alternatives: ["-i"]
      type: "file"
      example: "input.h5ad"
      description: "Input file that will be normalized"
      required: true
    - name: "--output"
      alternatives: ["-o"]
      type: "file"
      direction: "output"
      example: "output.h5ad"
      description: "Output data labeled"
      required: true
  resources:
    - type: r_script
      path: script.R
  test_resources:
    - type: python_script
      path: test_script.py
    - type: file
      path: "../../../../../resources_test/label_projection/pancreas/toy_preprocessed_data.h5ad"
platforms:
  - type: docker
    image: eddelbuettel/r2u:22.04
    setup:
      - type: r
        cran: [ Matrix, scran, BiocParallel, rlang, anndata]
      - type: apt
        packages: [ libhdf5-dev, libgeos-dev, python3, python3-pip, python3-dev, python-is-python3 ]
      - type: python
        pip: [anndata<0.8, scanpy]
  - type: nextflow
