# see https://github.com/openproblems-bio/openproblems/blob/9ebb777b3b76337e731a3b99f4bf39462a15c4cc/openproblems/tasks/dimensionality_reduction/methods/ivis.py

__merge__: ../../api/comp_method.yaml
functionality:
  name: "ivis"
  info:
    label: "ivis"
    summary: "Structure-preserving dimensionality reduction using a siamese neural network trained on triplets."
    description: |
      ivis is a machine learning library for reducing dimensionality of very large datasets using Siamese Neural Networks.
      ivis preserves global data structures in a low-dimensional space, adds new data points to existing embeddings using
      a parametric mapping function, and scales linearly to millions of observations.
    reference: szubert2019structurepreserving
    repository_url: "https://github.com/beringresearch/ivis"
    documentation_url: "https://github.com/beringresearch/ivis#readme"
    v1:
      path: openproblems/tasks/dimensionality_reduction/methods/ivis.py
      commit: 93d2161a08da3edf249abedff5111fb5ce527552
    preferred_normalization: log_cp10k
    variants:
      ivis_logCPM_1kHVG:
  arguments:
    - name: '--n_pca_dims'
      type: integer
      default: 50
      description: Number of principal components of PCA to use.
    - name: "--n_hvg"
      type: integer
      description: Number of highly variable genes to subset to. If not specified, the input matrix will not be subset.
      default: 1000
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.4
    setup:
      - type: python
        packages:
          - ivis[cpu]
          - tensorflow<2.16
  - type: nextflow
    directives:
      label: [midtime, highmem, highcpu]
