# use metric api spec
__merge__: ../../api/comp_metric_embedding.yaml
functionality:
  name: pcr
  description: PCA regression
  info:
    metrics:
      - name: pcr
        pretty_name: PCR
        summary:
        description:
        reference: luecken2022benchmarking
        repository_url: "The comparison of explained variance by batch before and after integration."
        documentation_url: |
          "This compares the explained variance by batch before and after integration. It
          returns a score between 0 and 1 (scaled=True) with 0 if the variance
          contribution hasnâ€™t changed. The larger the score, the more different the
          variance contributions are before and after integration."
        v1_url: openproblems/tasks/_batch_integration/batch_integration_embed/metrics/pcr.py
        v1_commit: 29803b95c88b4ec5921df2eec7111fd5d1a95daf
        min: 0
        max: 1
        maximize: true

  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: mumichae/scib-base:1.1.3
    setup:
      - type: python
        pypi: 
          - pyyaml
  - type: nextflow
