functionality:
  name: "data_loader"
  namespace: "common"
  version: "dev"
  description: "Load datasets"
  authors:
    - name: "Michaela Mueller "
      roles: [ maintainer, author ]
      props: { github: mumichae }
  arguments:
    - name: "--output"
      alternatives: ["-o"]
      type: "file"
      direction: "output"
      deafult: "output.h5ad"
      description: "Output h5ad file of the cleaned dataset"
      required: true
    - name: "--url"
      type: "string"
      description: "URL of dataset"
      required: true
    - name: "--name"
      type: "string"
      default: "pbmc"
      description: "Name of dataset"
      required: true
  resources:
    - type: python_script
      path: script.py
  tests:
    - type: python_script
      path: test.py
platforms:
  - type: docker
    image: "python:3.8"
    setup:
      - type: python
        packages:
          - scanpy
          - scprep
  - type: native
  - type: nextflow
