__merge__: ../api/comp_process_dataset.yaml
functionality:
  name: "process_dataset"
  arguments:
    - name: "--dataset_id"
      type: "string"
      description: "New dataset ID"
      required: false
    - name: "--swap"
      type: "boolean"
      description: "Swap mod1 and mod2"
      default: false
  resources:
    - type: r_script
      path: script.R
platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_r:1.0.4
  - type: nextflow
    directives:
      label: [midtime, midmem, lowcpu]
