name: validate_dataset_with_schema
namespace: files
summary: Check the format of a file against a schema
description: Checks if the file has the necessary data structures as defined in a schema.
argument_groups:
  - name:  Inputs
    arguments:
      - name: --input
        type: file
        required: true
        description: An input file. Can be an .h5ad, .parquet, .csv, or .tsv file.
      - name: --schema
        type: file
        required: true
        description: A schema file for the input object.
  - name: Arguments
    arguments:
      - name: --stop_on_error
        type: boolean
        default: false
        description: Whether or not to stop with exit code 1 if the input file does not adhere to the schema.
  - name: Output
    arguments:
      - name: --output
        type: file
        required: true
        description: If specified, this file will contain a structured log of which checks succeeded (or not).
        example: checks.json
        direction: output
resources:
  - type: python_script
    path: script.py
test_resources:
  - path: /resources_test/common/pancreas
  - type: python_script
    path: test.py
engines:
  - type: docker
    image: openproblems/base_python:1.0.0
    test_setup:
      - type: python
        packages: viashpy
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [midtime, midmem, midcpu]
