functionality:
  name: "process_datasets"
  namespace: "denoising/workflows"
  argument_groups:
    - name: Inputs
      arguments:
        - name: "--input"
          required: true
          example: dataset.h5ad
          __merge__: "/src/tasks/denoising/api/file_common_dataset.yaml"
    - name: Schemas
      arguments:
        - name: "--dataset_schema"
          type: "file"
          description: "The schema of the dataset to validate against"
          required: true
          default: "src/tasks/denoising/api/file_common_dataset.yaml"
    - name: Outputs
      arguments:
        - name: "--output_train"
          __merge__: "/src/tasks/denoising/api/file_train.yaml"
          direction: output
          required: true
        - name: "--output_test"
          __merge__: "/src/tasks/denoising/api/file_test.yaml"
          direction: output
          required: true
  resources:
    - type: nextflow_script
      path: main.nf
      entrypoint: run_wf
  dependencies:
    - name: common/check_dataset_schema
    - name: denoising/process_dataset
platforms:
  - type: nextflow
