repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        exclude: \.(ai|gz|md)$
      - id: requirements-txt-fixer
        files: .*requirements.*\.txt
  - repo: https://github.com/timothycrosley/isort
    rev: 5.11.5
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        args: ['--target-version', 'py36']
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.4
    hooks:
      - id: autopep8
  - repo: https://github.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        args: [openproblems]
        additional_dependencies: ['hacking']
  - repo: https://github.com/lorenzwalthert/precommit
    rev: v0.1.3
    hooks:
    -   id: parsable-R
    -   id: style-files
    -   id: lintr
        verbose: true
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.32.0
    hooks:
      - id: markdownlint-fix
        exclude: (SAGEMAKER.md|.github/ISSUE_TEMPLATE/bug_report.md|.github/pull_request_template.md)
  - repo: https://github.com/FlamingTempura/bibtex-tidy
    rev: "8838095"
    hooks:
    - id: bibtex-tidy
      args: ['--omit', 'abstract', '--sort', '--duplicates', '--sort-fields', '--trailing-commas']
