language: python
python:
  - 3.7
sudo: required
dist: xenial
addons:
  apt:
    packages:
      - libhdf5-dev
      - pandoc
      - gfortran
      - libblas-dev
      - liblapack-dev
      - libedit-dev
      - llvm-dev
cache:
  - pip
  - apt
  - directories:
      - $HOME/R/Library
      - $HOME/.singularity
before_install:
  - >-
    sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys
    E298A3A825C0D65DFD57CBB651716619E084DAB9
  - >-
    echo "deb http://cran.rstudio.com/bin/linux/ubuntu xenial-cran35/" | sudo
    tee -a /etc/apt/sources.list
  - curl http://neuro.debian.net/_static/neuro.debian.net.asc | sudo apt-key add
  - wget -O- http://neuro.debian.net/lists/xenial.us-nh.full | sudo tee /etc/apt/sources.list.d/neurodebian.sources.list
  - sudo apt-get update -qq
  - sudo apt-get install -yq --no-install-suggests --no-install-recommends r-base-core=3.6\*
  - sudo apt-get install -yq --no-install-suggests --no-install-recommends singularity-container
  - export R_LIBS_USER="$HOME/R/Library"
  - 'echo ".libPaths(c(''$R_LIBS_USER'', .libPaths()))" >> $HOME/.Rprofile'
install:
  - pip install -U .
script:
  - python -c "import openproblems"
  - 'pip install -U .[test]'
  - black . --check --diff --exclude=website
  - nose2 openproblems
after_success:
  - coveralls
deploy:
  provider: script
  skip_cleanup: true
  script: cd scripts && chmod +x evaluate.sh && ./evaluate.sh
  on:
    tags: true
    branch: master
