functionality:
  name: run
  namespace: common/process_dataset_metadata
  description: >-
    This workflow transforms the meta information of the datasets into a format
    that can be used by the website.
  argument_groups:
    - name: Inputs
      arguments:
        - name: "--input"
          type: file
          required: true
          direction: input
          example: meta.yaml
    - name: Outputs
      arguments:
        - name: "--output"
          type: file
          required: true
          direction: output
          default: $id.json
  resources:
    - type: nextflow_script
      path: main.nf
      entrypoint: run_wf
  dependencies: 
    - name: common/process_task_results/yaml_to_json
platforms:
  - type: nextflow