type: file
example: "resources_test/denoising/pancreas/test.h5ad"
info:
  label: "Test data"
  summary: The subset of molecules used for the test dataset
  slots:
    layers: 
      - type: integer
        name: counts
        description: Raw counts
        required: true
    uns:
      - type: string
        name: dataset_id
        description: "A unique identifier for the dataset"
        required: true
      - name: dataset_name
        type: string
        description: Nicely formatted name.
        required: true
      - type: string
        name: dataset_url
        description: Link to the original source of the dataset.
        required: false
      - name: dataset_reference
        type: string
        description: Bibtex reference of the paper in which the dataset was published.
        required: false
      - name: dataset_summary
        type: string
        description: Short description of the dataset.
        required: true
      - name: dataset_description
        type: string
        description: Long description of the dataset.
        required: true
      - name: dataset_organism
        type: string
        description: The organism of the sample in the dataset.
        required: false