# use method api spec
__merge__: ../../api/comp_method_embedding.yaml
functionality:
  name: scvi
  description: Run scVI on adata object, use feature output
  info:
    type: method
    method_name: scVI
    paper_reference: "lopez2018deep"
    code_url: https://github.com/YosefLab/scvi-tools"
    v1_url: openproblems/tasks/_batch_integration/batch_integration_graph/methods/scvi.py
    v1_commit: 29803b95c88b4ec5921df2eec7111fd5d1a95daf
    preferred_normalization: log_cpm
    variants:
      scvi_full_unscaled:
      scvi_hvg_unscaled:
        hvg: true
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: mumichae/scib-base:1.0.2
    setup:
      - type: python
        pypi:
          - scvi-tools
          - pyyaml
  - type: nextflow
