functionality:
  name: "subsample"
  namespace: "label_projection/data_processing"
  version: "dev"
  description: "Component to generate a toy data for tests finality"
  authors:
    - name: "Scott Gigante"
      roles: [ author ]
      props: { github: scottgigante }
    - name: "Vinicius Saraiva Chagas"
      roles: [ maintainer ]
      props: { github: chagasVinicius }
  arguments:
    - name: "--input"
      type: "file"
      description: "Input data to be resized"
      required: true
    - name: "--keep_celltype_categories"
      type: "string"
      multiple: true
      description: "Categories indexes to be selected"
      required: false
    - name: "--keep_batch_categories"
      type: "string"
      multiple: true
      description: "Categories indexes to be selected"
      required: false
    - name: "--even"
      type: "boolean_true"
    - name: "--output"
      alternatives: ["-o"]
      type: "file"
      direction: "output"
      default: "toy_data.h5ad"
      description: "Output h5ad file resized"
      required: true
  resources:
    - type: python_script
      path: script.py
  tests:
    - type: python_script
      path: test_script.py
    - type: file
      path: "../../resources/pancreas"
platforms:
  - type: native
  - type: docker
    image: "python:3.8"
    setup:
      - type: python
        packages:
          - scprep
          - scanpy
          -  "anndata<0.8"
  - type: nextflow
