functionality:
  name: "process_datasets"
  namespace: "match_modalities/workflows"
  argument_groups:
    - name: Inputs
      arguments:
        - name: "--input_mod1"
          __merge__: "/src/tasks/match_modalities/api/file_common_dataset_mod1.yaml"
          required: true
          direction: input
        - name: "--input_mod2"
          __merge__: "/src/tasks/match_modalities/api/file_common_dataset_mod2.yaml"
          required: true
          direction: input
    - name: Outputs
      arguments:
        - name: "--output_mod1"
          __merge__: /src/tasks/match_modalities/api/file_dataset_mod1.yaml
          required: true
          direction: output
        - name: "--output_mod2"
          __merge__: /src/tasks/match_modalities/api/file_dataset_mod2.yaml
          required: true
          direction: output
        - name: "--output_solution_mod1"
          __merge__: /src/tasks/match_modalities/api/file_solution_mod1.yaml
          required: true
          direction: output
        - name: "--output_solution_mod2"
          __merge__: /src/tasks/match_modalities/api/file_solution_mod2.yaml
          required: true
          direction: output
  resources:
    - type: nextflow_script
      path: main.nf
      entrypoint: run_wf
    - type: file
      path: "/src/tasks/match_modalities/api/file_common_dataset_mod1.yaml"
    - type: file
      path: "/src/tasks/match_modalities/api/file_common_dataset_mod2.yaml"
  dependencies:
    - name: common/check_dataset_schema
    - name: match_modalities/process_dataset
platforms:
  - type: nextflow
