__merge__: ../../api/comp_method.yaml
functionality:
  name: "knn_smoothing"
  namespace: "denoising/methods"
  description: "iterative K-nearest neighbor smoothing"
  info:
    type: method
    method_name: KNN Smoothing
    paper_reference: "wagner2018knearest"
    code_url: "https://github.com/yanailab/knn-smoothing"
    v1_url: openproblems/tasks/denoising/methods/knn_smoothing.py
    v1_commit: 29803b95c88b4ec5921df2eec7111fd5d1a95daf
    variants: 
      knn_smoothing:
    preferred_normalization: counts
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: "python:3.10"
    setup:
      - type: python
        packages:
          - "anndata>=0.8"
          - pyyaml
          - scipy
        github:
          - scottgigante-immunai/knn-smoothing@python_package
  - type: nextflow
    directives: 
      label: [ highmem, highcpu ]
