__merge__: ../../api/comp_method.yaml
functionality:
  name: "knn_smoothing"
  namespace: "denoising/methods"
  description: "iterative K-nearest neighbor smoothing"
  info:
    type: method
    label: knn_smooth
    # paper_name: "K-nearest neighbor smoothing for high-throughput"
    # paper_url: "https://www.biorxiv.org/content/10.1101/217737v3"
    # paper_year: 2018
    paper_doi: "10.1101/217737"
    code_url: "https://github.com/yanailab/knn-smoothing"
    v1_url: /openproblems/tasks/denoising/methods/knn_smoothing.py
    v1_commit: bbecf4e9ad90007c2711394e7fbd8e49cbd3e4a1
    preferred_normalization: counts
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: "python:3.10"
    setup:
      - type: python
        packages:
          - "anndata>=0.8"
          - scipy
        github:
          - yanailab/knn-smoothing@python_package
  - type: nextflow
    directives: 
      label: [ highmem, highcpu ]
