__merge__: ../api/get_info.yaml
functionality:
  name: "get_metric_info"
  description: "Extract metric info"
  resources:
    - type: r_script
      path: script.R
  test_resources:
    - type: file
      path: /resources_test/common/task_metadata/metric_configs.yaml
      dest: test_file.yaml
platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_r:1.0.4
    setup:
      - type: r
        cran: [ purrr, yaml, rlang, processx ]
  - type: nextflow
    directives:
      label: [lowmem, lowtime, lowcpu]
