functionality:
  name: "log_cpm"
  namespace: "label_projection/data_processing/normalize"
  version: "dev"
  description: "Normalize data"
  authors:
    - name: "Scott Gigante"
      roles: [ author ]
      props: { github: scottgigante }
    - name: "Vinicius Chagas"
      roles: [ maintainer ]
      props: { github: chagasVinicius }
  arguments:
    - name: "--input"
      alternatives: ["-i"]
      type: "file"
      example: "input.h5ad"
      description: "Input file that will be used to generate predictions"
      required: true
    - name: "--output"
      alternatives: ["-o"]
      type: "file"
      direction: "output"
      example: "output.h5ad"
      description: "Output data labeled"
      required: true
  resources:
    - type: python_script
      path: script.py
  tests:
    - type: python_script
      path: test_script.py
    - type: file
      path: "../../../resources/pancreas/toy_preprocessed_data.h5ad"
platforms:
  - type: docker
    image: "python:3.8"
    setup:
      - type: python
        packages:
          - scanpy
          - "anndata<0.8"
  - type: nextflow
