functionality:
  name: "dataset_simulator"
  namespace: "spatial_decomposition"
  info:
    type: dataset_simulator
    type_info:
      label: Dataset simulator
      summary: Simulate cell aggregates from single-cell data.
      description: |
        The dataset simulator creates cell-aggregates from the single-cell dataset by sampling from a Dirichlet distribution. The simulated data consists of the the spatial expression matrix, the XY coordinates of the spots, the cell-type proportions in each spot, and the reference single-cell data.
      variants: 
        alpha_1:
          alpha: 1
        alpha_5:
          alpha: 5
        alpha_0_5:
          alpha: 0.5
  arguments:
    - name: "--input"
      type: file
      description: Single-cell reference dataset
      direction: input
      example: "resources_test/common/cxg_mouse_pancreas_atlas/dataset.h5ad"
      info:
        slots:
          layers:
            - type: integer
              name: counts
              description: Raw counts.
              required: true
          obs:
            - type: string
              name: cell_type
              description: Cell type label IDs.
              required: true
            - type: string
              name: batch
              description: A batch identifier. This label is very context-dependent and may be a combination of the tissue, assay, donor, etc.
              required: true
          var:
            - type: boolean
              name: hvg
              description: Whether or not the feature is considered to be a 'highly variable gene'
              required: false
            - type: integer
              name: hvg_score
              description: A ranking of the features by hvg.
              required: false
          obsm:
            - type: double
              name: X_pca
              description: The resulting PCA embedding.
              required: false
          uns:
            - type: string
              name: dataset_id
              description: "A unique identifier for the dataset"
              required: true
            - name: dataset_name
              type: string
              description: Nicely formatted name.
              required: true
            - type: string
              name: dataset_url
              description: Link to the original source of the dataset.
              required: false
            - name: dataset_reference
              type: string
              description: Bibtex reference of the paper in which the dataset was published.
              required: false
            - name: dataset_summary
              type: string
              description: Short description of the dataset.
              required: true
            - name: dataset_description
              type: string
              description: Long description of the dataset.
              required: true
            - name: dataset_organism
              type: string
              description: The organism of the sample in the dataset.
              required: false
    - name: "--alpha"
      type: double
      description: Alpha value to use for generating synthetic dataset
      default: 1.0
    - name: "--n_obs"
      type: integer
      description: Number of spatial observations to generate. Default value is 100.
      default: 100
    - name: "--cell_lb"
      type: integer
      description: Lower bound for number of cells at each spot. Default value is 10.
      default: 10
    - name: "--cell_ub"
      type: integer
      description: Upper bound for number of cells at each spot. Default value is 30.
      default: 30
    - name: "--umi_lb"
      type: integer
      description: Lower bound for number of cells at each spot. Default value is 1000.
      default: 1000
    - name: "--umi_ub"
      type: integer
      description: Upper bound for number of UMIs at each spot. Default value is 5000.
      default: 5000
    - name: "--simulated_data"
      type: file
      direction: output
      description: Simulated dataset
      required: false
      example: dataset_simulated.h5ad
      info:
        slots:
          layers:
            - type: integer
              name: counts
              description: Raw counts.
              required: true
          obs:
            - type: string
              name: cell_type
              description: Cell type label IDs.
              required: true
            - type: string
              name: batch
              description: A batch identifier. This label is very context-dependent and may be a combination of the tissue, assay, donor, etc.
              required: true
          var:
            - type: boolean
              name: hvg
              description: Whether or not the feature is considered to be a 'highly variable gene'
              required: false
            - type: integer
              name: hvg_score
              description: A ranking of the features by hvg.
              required: false
          obsm:
            - type: double
              name: X_pca
              description: The resulting PCA embedding.
              required: false
            - type: double
              name: coordinates
              description: XY coordinates for each spot.
              required: true
            - type: double
              name: proportions_true
              description: True cell type proportions for each spot.
              required: true
          uns:
            - type: string
              name: cell_type_names
              description: Cell type names corresponding to values in `cell_type`.
              required: true
            - type: string
              name: dataset_id
              description: "A unique identifier for the dataset"
              required: true
            - name: dataset_name
              type: string
              description: Nicely formatted name.
              required: true
            - type: string
              name: dataset_url
              description: Link to the original source of the dataset.
              required: false
            - name: dataset_reference
              type: string
              description: Bibtex reference of the paper in which the dataset was published.
              required: false
            - name: dataset_summary
              type: string
              description: Short description of the dataset.
              required: true
            - name: dataset_description
              type: string
              description: Long description of the dataset.
              required: true
            - name: dataset_organism
              type: string
              description: The organism of the sample in the dataset.
              required: false
  resources:
    - type: python_script
      path: script.py
  test_resources:
    - type: python_script
      path: /src/common/comp_tests/run_and_check_adata.py
    - path: /resources_test/common/cxg_mouse_pancreas_atlas
      dest: resources_test/common/cxg_mouse_pancreas_atlas
platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.2
    setup:
      - type: python
        packages: [numpy, scanpy]
  - type: nextflow
    directives: 
      label: [ midtime, highmem, highcpu ]
  - type: native
