__merge__: ../../api/comp_method.yaml

functionality:
  name: tangram
  info:
    label: Tangram
    summary: "Tanagram maps single-cell gene expression data onto spatial gene expression data by fitting gene expression on shared genes"
    description: |
      Tangram is a method to map gene expression signatures from scRNA-seq data to spatial data. It performs the cell type mapping by learning a similarity matrix between single-cell and spatial locations based on gene expression profiles.
    preferred_normalization: counts
    reference: biancalani2021deep
    documentation_url: https://tangram-sc.readthedocs.io/en/latest/index.html
    repository_url: https://github.com/broadinstitute/Tangram

  arguments:
    - name: "--num_epochs"
      type: integer
      default: 1000
      description: Number of epochs to use while mapping single cells to spatial locations.
    - name: "--n_markers"
      type: integer
      default: 100
      description: Number of marker genes to use.

  resources:
    - type: python_script
      path: script.py

platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.4
    setup:
      - type: python
        packages: tangram-sc
  - type: native
  - type: nextflow
    directives:
      label: [midtime,midmem, midcpu]
