__merge__: ../../api/comp_method.yaml
functionality:
  name: "phate"
  namespace: "dimensionality_reduction/methods"
  description: "Potential of heat-diffusion for affinity-based transition embedding"
  info:
    type: method
    label: PHATE
    v1_url: openproblems/tasks/dimensionality_reduction/methods/phate.py
    v1_commit: 4baa8619e232fec2e3bcb3fb73d2f991d16c6f69
    preferred_normalization: sqrt_cpm
    variants:
      phate:
      phate_sqrt:
        gamma: 0
      phate_logCPM_1kHVG:
        num_hvg_genes: 1000
        preferred_normalization: log_cpm
  arguments:
    - name: '--n_pca'
      type: integer
      default: 50
      description: Number of principal components of PCA to use.
    - name: '--gamma'
      type: double
      description: Gamma value
      default: 1
    - name: '--num_hvg_genes'
      type: integer
      description: |
        Subset to the highly variable genes as specified
        by the .var['hvg_score'] column.
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: "python:3.10"
    setup:
      - type: python
        packages:
          - "anndata>=0.8"
          - phate==1.0.*
          - scprep
          - pyyaml
          - "scikit-learn<1.2"
  - type: nextflow
    directives: 
      label: [ highmem, highcpu ]
