__merge__: ../../api/comp_control_method.yaml
functionality:
  name: mean_per_gene
  info:
    label: Mean per gene
    summary: Returns the mean expression value per gene.
    description: Returns the mean expression value per gene.
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.4
  - type: nextflow
    directives:
      label: [midtime, lowmem, lowcpu]
  