__merge__: ../../api/comp_method.yaml
functionality:
  name: "scanvi"
  info:
    pretty_name: SCANVI
    summary: "ScANVI predicts cell type labels for unlabelled test data by leveraging cell type labels, modelling uncertainty and using deep neural networks with stochastic optimization."
    description: |
      "single-cell ANnotation using Variational Inference is a
      semi-supervised variant of the scVI(Lopez et al. 2018) algorithm. Like scVI,
      scANVI uses deep neural networks and stochastic optimization to model
      uncertainty caused by technical noise and bias in single - cell
      transcriptomics measurements. However, scANVI also leverages cell type labels
      in the generative modelling. In this approach, scANVI is used to predict the
      cell type labels of the unlabelled test data."
    reference: "lotfollahi2020query"
    repository_url: "https://github.com/YosefLab/scvi-tools"
    documentation_url: https://scarches.readthedocs.io/en/latest/scanvi_surgery_pipeline.html
    v1_url: openproblems/tasks/label_projection/methods/scvi_tools.py
    v1_commit: 4bb8a7e04545a06c336d3d9364a1dd84fa2af1a4
    preferred_normalization: log_cpm
    variants:
      scanvi_all_genes:
      scanvi_hvg:
        num_hvg: 2000
  arguments:
    - name: "--num_hvg"
      type: integer
      description: "The number of HVG genes to subset to."
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: nvcr.io/nvidia/pytorch:22.12-py3
    setup:
      - type: python
        packages: 
          - pyyaml
          - "anndata~=0.8.0"
          - scarches
  - type: nextflow
    directives: 
      label: [ midmem, highcpu, gpu ]
