__merge__: ../../api/comp_method.yaml
functionality:
  name: diffusion_map
  info:
    label: Diffusion Map
    summary: Finding meaningful geometric descriptions of datasets using diffusion maps.
    description: Implements diffusion map method of data parametrization, including creation and visualization of diffusion map, clustering with diffusion K-means and regression using adaptive regression model. 
    reference: coifman2006diffusion
    documentation_url: https://bioconductor.org/packages/release/bioc/html/destiny.html
    repository_url: https://github.com/theislab/destiny
    v1:
      path: openproblems/tasks/dimensionality_reduction/methods/diffusion_map.py
      commit: b3456fd73c04c28516f6df34c57e6e3e8b0dab32
    preferred_normalization: log_cp10k
  resources:
    - type: r_script
      path: script.R
  arguments:
    - name: "--n_dim"
      type: integer
      description: Number of dimensions.
      default: 3
platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_r:1.0.2
    setup:
      - type: r
        bioc: destiny
  - type: nextflow
    directives: 
      label: [ midtime, highmem, highcpu ]
