__merge__: ../../api/comp_method.yaml

functionality:
  name: nnls
  info:
    label: NNLS
    summary: "NNLS is a decomposition method based on Non-Negative Least Square Regression."
    description: |
      NonNegative Least Squares (NNLS), is a convex optimization problem with convex constraints. It was used by the AutoGeneS method to infer cellular proporrtions by solvong a multi-objective optimization problem.
    preferred_normalization: counts
    reference: "aliee2021autogenes"
    documentation_url: https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.nnls.html
    repository_url: https://github.com/scipy/scipy

  resources:
    - type: python_script
      path: script.py

platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.4
    setup:
      - type: python
        packages: 
          - numpy
          - scipy
  - type: native
  - type: nextflow
    directives:
      label: [midtime, midmem, midcpu]
