__merge__: ../api/get_info.yaml
functionality:
  name: "get_dataset_info"
  description: "Extract dataset info and convert to expected format for website results"
  resources:
    - type: r_script
      path: script.R
  test_resources:
    - type: file
      path: /resources_test/common/task_metadata/dataset_info.yaml
      dest: test_file.yaml
platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_r:1.0.4
    setup:
      - type: r
        cran: [ purrr, yaml, rlang, processx ]
  - type: nextflow
    directives:
      label: [lowmem, lowtime, lowcpu]
