__merge__: ../../api/comp_method.yaml

functionality:
  name: stereoscope

  info:
    label: Stereoscope
    summary: "Stereoscope is a decomposition method based on Negative Binomial regression."
    description: |
      Stereoscope is a decomposition method based on Negative Binomial regression. It is similar in scope and implementation to cell2location but less flexible to incorporate additional covariates such as batch effects and other type of experimental design annotations.
    preferred_normalization: counts
    reference: andersson2020single
    documentation_url: https://docs.scvi-tools.org/en/stable/user_guide/models/stereoscope.html
    repository_url: https://github.com/scverse/scvi-tools

  arguments: 
    - name: "--max_epochs_sc"
      type: integer
      default: 100
      description: Number of of epochs to train RNAStereoscope model.
    - name: "--max_epochs_sp"
      type: integer
      default: 1000
      description: Number of of epochs to train SpatialStereoscope model.

  resources:
    - type: python_script
      path: script.py

platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_pytorch_nvidia:1.0.4
    setup:
      - type: python
        packages: 
          - scvi-tools>=1.1.0
      - type: docker
        run: |
          pip install -U "jax[cuda12_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
  - type: native
  - type: nextflow
    directives:
      label: [hightime, midmem, midcpu, gpu]
