functionality:
  name: "run_benchmark"
  namespace: "match_modalities/workflows"
  argument_groups:
    - name: Inputs
      arguments:
        - name: "--input_mod1"
          __merge__: /src/tasks/match_modalities/api/file_dataset_mod1.yaml
          direction: input
          required: true
        - name: "--input_mod2"
          __merge__: /src/tasks/match_modalities/api/file_dataset_mod2.yaml
          direction: input
          required: true
        - name: "--input_solution_mod1"
          __merge__: /src/tasks/match_modalities/api/file_solution_mod1.yaml
          direction: input
          required: true
        - name: "--input_solution_mod2"
          __merge__: /src/tasks/match_modalities/api/file_solution_mod2.yaml
          direction: input
          required: true
    - name: Outputs
      arguments:
        - name: "--output_scores"
          type: file
          required: true
          direction: output
          description: A yaml file containing the scores of each of the methods
          default: score_uns.yaml
        - name: "--output_method_configs"
          type: file
          required: true
          direction: output
          default: method_configs.yaml
        - name: "--output_metric_configs"
          type: file
          required: true
          direction: output
          default: metric_configs.yaml
        - name: "--output_dataset_info"
          type: file
          required: true
          direction: output
          default: dataset_uns.yaml
        - name: "--output_task_info"
          type: file
          required: true
          direction: output
          default: task_info.yaml
  resources:
    - type: nextflow_script
      path: main.nf
      entrypoint: run_wf
    - type: file
      path: "/src/tasks/match_modalities/api/task_info.yaml"
  dependencies:
    - name: common/check_dataset_schema
    - name: common/extract_scores
    - name: match_modalities/control_methods/random_features
    - name: match_modalities/control_methods/true_features
    - name: match_modalities/methods/fastmnn
    - name: match_modalities/methods/scot
    - name: match_modalities/methods/harmonic_alignment
    - name: match_modalities/methods/procrustes
    - name: match_modalities/metrics/knn_auc
    - name: match_modalities/metrics/mse
platforms:
  - type: nextflow