__merge__: ../../api/comp_control_method.yaml
functionality:
  name: "majority_vote"
  info:
    label: Majority Vote
    summary: "A control-type method that predicts all cells to belong to the most abundant cell type in the dataset"
    description: "A control-type method that predicts all cells to belong to the most abundant cell type in the dataset"
    v1:
      path: openproblems/tasks/label_projection/methods/baseline.py
      commit: b3456fd73c04c28516f6df34c57e6e3e8b0dab32
    variants:
      majority_vote:
    preferred_normalization: counts
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.4
  - type: nextflow
    directives: 
      label: [midtime, lowmem, lowcpu]
