__merge__: ../../api/comp_control_method.yaml
functionality:
  name: "majority_vote"
  info:
    label: Majority Vote
    summary: "A control-type method that predicts all cells to belong to the most abundant cell type in the dataset"
    description: "A control-type method that predicts all cells to belong to the most abundant cell type in the dataset"
    v1:
      path: openproblems/tasks/label_projection/methods/baseline.py
      commit: b460ecb183328c857cbbf653488f522a4034a61c
    variants:
      majority_vote:
    preferred_normalization: counts
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.0
  - type: nextflow
    directives: 
      label: [ lowmem, lowcpu ]
