# use method api spec
__merge__: ../../../api/comp_control_method_embedding.yaml
functionality:
  name: celltype_embed
  namespace: batch_integration/control_methods/perfect_integration
  info:
    label: Perfect embedding by cell type
    summary: "Cells are embedded as a one-hot encoding of celltype labels"
    description: "Cells are embedded as a one-hot encoding of celltype labels"
    v1:
      path: openproblems/tasks/_batch_integration/_common/methods/baseline.py
      commit: b3456fd73c04c28516f6df34c57e6e3e8b0dab32
    preferred_normalization: log_cp10k
  resources:
    - type: python_script
      path: script.py
    - path: ../../utils.py
platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.4
  - type: nextflow
    directives:
      label: [midtime, lowmem, lowcpu]