name: zenodo_slidetags
namespace: datasets/loaders/spatial
description: |
  Download a compressed file containing gene expression matrix and spatial locations from zenodo.
argument_groups:
  - name: Inputs
    arguments:
      - name: --input_data
        type: string
        description: URL to the file.
        required: true
  - name: Outputs
    arguments:
      - name: --dataset
        type: file
        direction: output
        description: Output h5ad file
        required: true
        example: dataset.h5ad
  - name: Metadata
    arguments:
      - name: --dataset_id
        type: string
        description: Unique identifier of the dataset.
        required: true
      - name: --dataset_name
        type: string
        description: Nicely formatted name.
        required: true
      - name: --dataset_url
        type: string
        description: Link to the original source of the dataset.
        required: false
      - name: --dataset_reference
        type: string
        description: Bibtex reference of the paper in which the dataset was published.
        required: false
      - name: --dataset_summary
        type: string
        description: Short description of the dataset.
        required: true
      - name: --dataset_description
        type: string
        description: Long description of the dataset.
        required: true
      - name: --dataset_organism
        type: string
        description: The organism of the dataset.
        required: false
  - name: Gene or spot filtering
    description: Arguments related to filtering cells and genes by counts.
    arguments:
      - name: --spot_filter_min_genes
        type: integer
        description: Remove spots with less than this number of genes.
        required: false
        example: 200
      - name: --spot_filter_min_counts
        type: integer
        description: Remove spots with less than this number of counts.
        required: false
      - name: --gene_filter_min_spots
        type: integer
        description: Remove genes expressed in less than this number of cells.
        required: false
        example: 50
      - name: --gene_filter_min_counts
        type: integer
        description: Remove genes with less than this number of counts.
        required: false
      - name: --remove_mitochondrial
        type: boolean
        description: Remove mitochondrial genes?
        required: false

resources:
  - type: python_script
    path: script.py
test_resources:
  - type: python_script
    path: test.py

engines:
  - type: docker
    image: openproblems/base_python:1.0.0
runners:
  - type: executable
  - type: nextflow
