functionality:
  name: "process_datasets"
  namespace: "dimensionality_reduction/workflows"
  argument_groups:
    - name: Inputs
      arguments:
        - name: "--input"
          __merge__: "/src/tasks/dimensionality_reduction/api/file_common_dataset.yaml"
          required: true
          direction: input
    - name: Outputs
      arguments:
        - name: "--output_dataset"
          __merge__: /src/tasks/dimensionality_reduction/api/file_dataset.yaml
          required: true
          direction: output
        - name: "--output_solution"
          __merge__: /src/tasks/dimensionality_reduction/api/file_solution.yaml
          required: true
          direction: output
  resources:
    - type: nextflow_script
      path: main.nf
      entrypoint: run_wf
    - type: file
      path: "/src/tasks/dimensionality_reduction/api/file_common_dataset.yaml"
  dependencies:
    - name: common/check_dataset_schema
    - name: dimensionality_reduction/process_dataset
platforms:
  - type: nextflow