# use metric api spec
__merge__: ../../api/comp_metric_embedding.yaml
functionality:
  name: cell_cycle_conservation
  description: Cell cycle conservation score based on cell cycle gene scoring
  info:
    v1_url: openproblems/tasks/_batch_integration/batch_integration_embed/metrics/cc_score.py
    v1_commit: 29803b95c88b4ec5921df2eec7111fd5d1a95daf
    paper_reference: luecken2022benchmarking
    metrics:
      - metric_id: cell_cycle_conservation
        metric_name: Cell Cycle Conservation
        min: 0
        max: 1
        maximize: true
  # arguments:
  #   - name: --organism
  #     type: string
  #     description: Name of organism to compute cell cycle scores on
  #     required: true
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: mumichae/scib-base:1.0.2
    setup:
      - type: python
        pypi: 
          - pyyaml
  - type: nextflow
