functionality:
  name: "run_benchmark"
  namespace: "dimensionality_reduction/workflows"
  argument_groups:
    - name: Inputs
      arguments:
        - name: "--id"
          type: "string"
          description: "The ID of the normalized dataset"
          required: true
        - name: "--input_dataset"
          type: "file"
          required: true
        - name: "--input_solution"
          type: "file"
          required: true
    - name: Outputs
      arguments:
        - name: "--output"
          direction: "output"
          type: file
          example: output.tsv
          required: true
  resources:
    - type: nextflow_script
      path: main.nf
      entrypoint: run_wf
  dependencies:
    - name: common/check_dataset_schema
    - name: common/extract_scores
    - name: dimensionality_reduction/control_methods/random_features
    - name: dimensionality_reduction/control_methods/true_features
    - name: dimensionality_reduction/methods/densmap
    - name: dimensionality_reduction/methods/neuralee
    - name: dimensionality_reduction/methods/pca
    - name: dimensionality_reduction/methods/phate
    - name: dimensionality_reduction/methods/tsne
    - name: dimensionality_reduction/methods/umap
    - name: dimensionality_reduction/metrics/coranking
    - name: dimensionality_reduction/metrics/density_preservation
    - name: dimensionality_reduction/metrics/distance_correlation
    - name: dimensionality_reduction/metrics/trustworthiness
  # test_resources:
  #   - type: nextflow_script
  #     path: main.nf
  #     entrypoint: test_wf
platforms:
  - type: nextflow