functionality:
  namespace: batch_integration
  info:
    type: process_dataset
    type_info:
      label: Data processor
      summary: A label projection dataset processor.
      description: |
        A component for processing a Common Dataset into a task-specific dataset.
  arguments:
    - name: "--input"
      __merge__: /src/datasets/api/file_common_dataset.yaml
      direction: input
      required: true
    - name: "--output_dataset"
      __merge__: file_dataset.yaml
      direction: output
      required: true
    - name: "--output_solution"
      __merge__: file_solution.yaml
      direction: output
      required: true
    - name: "--obs_label"
      type: "string"
      description: "Which .obs slot to use as label."
      default: "celltype"
    - name: "--obs_batch"
      type: "string"
      description: "Which .obs slot to use as batch covariate."
      default: "batch"
    - name: --hvgs
      type: integer
      description: Number of highly variable genes
      default: 2000
      required: false
    - name: --subset_hvg
      type: boolean
      description: Whether to subset to highly variable genes
      default: false
      required: false
  test_resources:
    - path: /resources_test/common/pancreas/
      dest: resources_test/common/pancreas/
    - type: python_script
      path: /src/common/comp_tests/run_and_check_adata.py