__merge__: "file_unintegrated.yaml"
type: file
example: "resources_test/batch_integration/pancreas/integrated_feature.h5ad"
info:
  prediction_type: feature
  label: "Integrated Feature"
  summary: Integrated AnnData HDF5 file.
  slots:
    layers:
      - type: double
        name: corrected_counts
        description: Corrected counts after integration
        required: true
    uns:
      - type: string
        name: method_id
        description: "A unique identifier for the method"
        required: true

      - type: string
        name: output_type
        description: what kind of output has been generated
        required: true