__merge__: "file_unintegrated.yaml"
type: file
example: "resources_test/batch_integration/pancreas/bbknn.h5ad"
info:
  prediction_type: graph
  label: "Integrated Graph"
  summary: Integrated AnnData HDF5 file.
  slots:
    obsp:
      - type: double
        name: connectivities
        description: Neighbors connectivities matrix.
        required: true
    uns:
      - type: string
        name: method_id
        description: "A unique identifier for the method"
        required: true
      - type: boolean
        name: hvg
        description: If the method was done on hvg or full
        required: true
      - type: string
        name: output_type
        description: what kind of output has been generated
        required: true
