# This file is based on the spec of the common dataset located at
# `src/datasets/api/file_common_dataset.yaml`. However, some fields
# such as obs.celltype and obs.batch are now required
type: file
example: "resources_test/common/pancreas/dataset.h5ad"
info:
  label: "Common Dataset"
  summary: A subset of the common dataset.
  slots:
    layers:
      - type: integer
        name: counts
        description: Raw counts
        required: true
      - type: double
        name: normalized
        description: Normalized expression values
        required: true
    obs:
      - type: string
        name: celltype
        description: Cell type information
        required: true
      - type: string
        name: batch
        description: Batch information
        required: true
    var:
      - type: boolean
        name: hvg
        description: Whether or not the feature is considered to be a 'highly variable gene'
        required: true
    obsm:
      - type: double
        name: X_pca
        description: The resulting PCA embedding.
        required: true
    obsp:
      - type: double
        name: knn_distances
        description: K nearest neighbors distance matrix.
        required: true
      - type: double
        name: knn_connectivities
        description: K nearest neighbors connectivities matrix.
        required: true
    uns:
      - type: string
        name: dataset_id
        description: "A unique identifier for the dataset"
        required: true
      - name: dataset_name
        type: string
        description: Nicely formatted name.
        required: true
      - type: string
        name: data_url
        description: Link to the original source of the dataset.
        required: false
      - name: data_reference
        type: string
        description: Bibtex reference of the paper in which the dataset was published.
        required: false
      - name: dataset_summary
        type: string
        description: Short description of the dataset.
        required: true
      - name: dataset_description
        type: string
        description: Long description of the dataset.
        required: true
      - name: dataset_organism
        type: string
        description: The organism of the sample in the dataset.
        required: false
      - type: string
        name: normalization_id
        description: "Which normalization was used"
        required: true
      - type: object
        name: knn
        description: Supplementary K nearest neighbors data.
        required: true

