# use metric api spec
__merge__: ../../api/comp_metric_embedding.yaml
functionality:
  name: pcr
  info:
    metrics:
      - name: pcr
        label: PCR
        summary: Compare explained variance by batch before and after integration
        description: |
          Principal component regression, derived from PCA, has previously been used to quantify
          batch removal. Briefly, the R2 was calculated from a linear regression of the
          covariate of interest (for example, the batch variable B) onto each principal component.
          The variance contribution of the batch effect per principal component was then
          calculated as the product of the variance explained by the ith principal component (PC)
          and the corresponding R2(PCi|B). The sum across all variance contributions by the batch
          effects in all principal components gives the total variance explained by the batch
          variable as follows:
          Var(ğ¶|ğµ)=âˆ‘ğ‘–=1ğºVar(ğ¶|PCğ‘–)Ã—ğ‘…2(PCğ‘–|ğµ),

          where Var(C|PCi) is the variance of the data matrix C explained by the ith principal
          component.
        reference: luecken2022benchmarking
        v1:
          path: openproblems/tasks/_batch_integration/batch_integration_embed/metrics/pcr.py
          commit: b3456fd73c04c28516f6df34c57e6e3e8b0dab32
        min: 0
        max: 1
        maximize: true
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.1
    setup:
      - type: python
        pypi:
          - scib==1.1.3
  - type: nextflow
    directives: 
      label: [ "midtime", midmem, lowcpu ]
