# use metric api spec
__merge__: ../../api/comp_metric_embedding.yaml
functionality:
  name: pcr
  info:
    metrics:
      - name: pcr
        label: PCR
        summary: "The comparison of explained variance by batch before and after integration."
        description: |
          "This compares the explained variance by batch before and after integration. It
          returns a score between 0 and 1 (scaled=True) with 0 if the variance
          contribution hasnâ€™t changed. The larger the score, the more different the
          variance contributions are before and after integration."
        reference: luecken2022benchmarking
        v1:
          path: openproblems/tasks/_batch_integration/batch_integration_embed/metrics/pcr.py
          commit: 29803b95c88b4ec5921df2eec7111fd5d1a95daf
        min: 0
        max: 1
        maximize: true
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_r:1.0.0
    setup:
      - type: python
        pypi: 
          - scanpy
          - scib==1.1.3
  - type: nextflow
