__merge__: ../../api/comp_method.yaml
functionality:
  name: "dca"
  info:
    label: DCA
    summary: "A deep autoencoder with ZINB loss function to address the dropout effect in count data"
    description: |
      "Deep Count Autoencoder

      Removes the dropout effect by taking the count structure, overdispersed nature and sparsity of the data into account 
      using a deep autoencoder with zero-inflated negative binomial (ZINB) loss function."
    reference: "eraslan2019single"
    documentation_url: "https://github.com/theislab/dca#readme"
    repository_url: "https://github.com/theislab/dca"
    v1:
      path: openproblems/tasks/denoising/methods/dca.py
      commit: 29803b95c88b4ec5921df2eec7111fd5d1a95daf
    variants: 
      dca:
    preferred_normalization: counts
  arguments:
    - name: "--epochs"
      type: "integer"
      default: 300
      description: "Number of total epochs in training"
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.0
    setup:
      - type: python
        packages:
          - "git+https://github.com/scottgigante-immunai/dca.git@patch-1"
  - type: nextflow
    directives: 
      label: [ highmem, highcpu ]
