functionality:
  name: "process_datasets"
  namespace: "predict_modality/workflows"
  argument_groups:
    - name: Inputs
      arguments:
        - name: "--input_rna"
          __merge__: "/src/tasks/predict_modality/api/file_common_dataset_rna.yaml"
          required: true
          direction: input
        - name: "--input_other_mod"
          __merge__: "/src/tasks/predict_modality/api/file_common_dataset_other_mod.yaml"
          direction: input
          required: true
    - name: Outputs
      arguments:
        - name: "--output_train_mod1"
          __merge__: /src/tasks/predict_modality/api/file_train_mod1.yaml
          direction: output
          required: true
        - name: "--output_train_mod2"
          __merge__: /src/tasks/predict_modality/api/file_train_mod2.yaml
          direction: output
          required: true
        - name: "--output_test_mod1"
          __merge__: /src/tasks/predict_modality/api/file_test_mod1.yaml
          direction: "output"
          required: true
        - name: "--output_test_mod2"
          __merge__: /src/tasks/predict_modality/api/file_test_mod2.yaml
          direction: output
          required: true
  resources:
    - type: nextflow_script
      path: main.nf
      entrypoint: run_wf
    - path: /src/wf_utils/helper.nf
  dependencies:
    - name: common/check_dataset_schema
    - name: predict_modality/process_dataset
platforms:
  - type: nextflow
