name: generate_dataset_metadata_for_website
namespace: reporting
description: >-
  This workflow transforms the meta information of the datasets into a format
  that can be used by the website.
argument_groups:
  - name: Inputs
    arguments:
      - name: "--input"
        type: file
        required: true
        direction: input
        example: meta.yaml
  - name: Outputs
    arguments:
      - name: "--output"
        type: file
        required: true
        direction: output
        default: meta.json
resources:
  - type: nextflow_script
    path: main.nf
    entrypoint: run_wf
dependencies: 
  - name: utils/yaml_to_json
runners:
  - type: nextflow