__merge__: ../../api/comp_control_method.yaml
functionality:
  name: "no_denoising"
  info:
    subtype: negative_control
    pretty_name: No Denoising
    summary: "negative control by copying train counts"
    description: "This method serves as a negative control, where the denoised data is a copy of the unaltered training data. This represents the scoring threshold if denoising was not performed on the data."
    v1_url: openproblems/tasks/denoising/methods/baseline.py
    v1_commit: 29803b95c88b4ec5921df2eec7111fd5d1a95daf
    variants:
      no_denoising:
    preferred_normalization: counts
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base-python:latest
  - type: nextflow
    directives: 
      label: [ midmem, midcpu ]
