__merge__: ../../api/comp_metric.yaml
functionality:
  name: "rmse"
  info:
    metrics:
      - name: rmse
        label: RMSE
        summary: "The residual after applying the Non-Negative Least Squares solver on the pairwise distances of an SVD."
        description: "The residual after applying the Non-Negative Least Squares solver on the pairwise distances of an SVD."
        reference: kruskal1964mds
        min: 0
        max: "+.inf"
        maximize: false
      - name: rmse_spectral
        label: RMSE Spectral
        summary: "The residual after applying the Non-Negative Least Squares solver on the pairwise distances of a spectral embedding."
        description: "The residual after applying the Non-Negative Least Squares solver on the pairwise distances of a spectral embedding."
        reference: coifman2006diffusion
        min: 0
        max: "+.inf"
        maximize: false
        v1:
          path: openproblems/tasks/dimensionality_reduction/metrics/root_mean_square_error.py 
          commit: b353a462f6ea353e0fc43d0f9fcbbe621edc3a0b
          note: This metric was ported but will probably be removed soon.
  arguments:
    - name: "--spectral"
      type: boolean_true
      description: Calculate the spectral root mean squared error.
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.1
    setup:
      - type: python
        packages:
          - umap-learn
          - scikit-learn
          - numpy
          - scipy
  - type: nextflow
    directives: 
      label: [ midmem, midcpu ]
