__merge__: ../../api/comp_normalization.yaml
functionality:
  name: "log_cp"
  description: "Normalize data using Log CP"
  resources:
    - type: python_script
      path: script.py
  arguments:
    - name: "--n_cp"
      type: integer
      default: 1e4
      description: "Number of counts per cell"
platforms:
  - type: docker
    image: openproblems/base_python:1.0.0
  - type: nextflow
    directives: 
      label: [midtime, midmem, midcpu]
