__merge__: ../api/comp_split_dataset.yaml
functionality:
  name: split_dataset
  namespace: batch_integration
  description: Preprocess adata object for data integration
  arguments:
    - name: "--obs_label"
      type: "string"
      description: "Which .obs slot to use as label."
      default: "celltype"
    - name: "--obs_batch"
      type: "string"
      description: "Which .obs slot to use as batch covariate."
      default: "batch"
    - name: --hvgs
      type: integer
      description: Number of highly variable genes
      default: 2000
      required: false
  resources:
    - type: python_script
      path: script.py
  test_resources:
    - type: python_script
      path: test.py
    - path: ../../../resources_test/common/pancreas/
platforms:
  - type: docker
    image: mumichae/scib-base:1.0.2
    setup:
      - type: python
        pypi: pyyaml
  - type: nextflow
