functionality:
  name: check_dataset_schema
  namespace: common
  description: Checks if the dataset has the necessary slots that are predefined in a schema.
  argument_groups:
    - name:  Inputs
      arguments:
        - name: --input
          type: file
          required: true
          description: A h5ad file.
        - name: --schema
          type: file
          required: true
          description: A schema file for the h5ad object.
    - name: Arguments
      arguments:
        - name: --stop_on_error
          type: boolean
          default: false
          description: Whether or not to stop with exit code 1 if the input file does not adhere to the schema.
    - name: Output
      arguments:
        - name: --output
          type: file
          required: true
          description: If specified, this file will contain a structured log of which checks succeeded (or not).
          example: checks.json
          direction: output
  resources:
    - type: python_script
      path: script.py
  test_resources:
    - path: /resources_test/common/pancreas
    - type: python_script
      path: test.py
platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.2
    test_setup:
      - type: python
        packages: viashpy
  - type: nextflow
    directives:
      label: [ midtime, midmem, midcpu ]
