functionality:
  name: "get_metric_info"
  namespace: "common"
  description: "Extract metric info"
  arguments:
    - name: "--input"
      type: "file"
      example: src
      description: "A source dir"
    - name: "--query"
      type: "string"
      description: "A task dir"
      example: label_projection
    - name: "--output"
      type: "file"
      direction: "output"
      default: "output.json"
      description: "Output json"
  resources:
    - type: r_script
      path: script.R
  test_resources:
    - path: ../../../src
    - type: python_script
      path: test.py
platforms:
  - type: docker
    image: eddelbuettel/r2u:22.04
    setup:
      - type: r
        cran: [ tidyverse ]
      - type: apt
        packages: [ curl, default-jdk ]
      - type: docker
        run: "curl -fsSL get.viash.io | bash -s -- --bin /usr/local/bin/"
    test_setup:
      - type: apt
        packages: [libhdf5-dev, libgeos-dev, python3, python3-pip, python3-dev, python-is-python3, git]
  - type: nextflow
  - type: native
