functionality:
  name: "knn_classifier"
  namespace: "label_projection/methods"
  version: "dev"
  description: "Nearest neighbor pattern classification"
  info:
    type: baseline
    label: KNN
  authors:
    - name: "Scott Gigante"
      roles: [ author ]
      props: { github: scottgigante }
    - name: "Vinicius Chagas"
      roles: [ maintainer ]
      props: { github: chagasVinicius }
  arguments:
    - name: "--input"
      alternatives: ["-i"]
      type: "file"
      example: "input.h5ad"
      description: "Input file that will be used to generate predictions"
      required: true
    - name: "--output"
      alternatives: ["-o"]
      type: "file"
      direction: "output"
      example: "output.h5ad"
      description: "Output data containing predictions"
      required: true
  resources:
    - type: python_script
      path: script.py
    - path: "../../utils.py"
  tests:
    - type: python_script
      path: ../unit_tests/test_method.py
    - path: ../../resources/pancreas/toy_normalized_log_scran_pooling_data.h5ad
    - path: ../../resources/pancreas/toy_normalized_log_cpm_data.h5ad
platforms:
  - type: docker
    image: "python:3.8"
    setup:
      - type: python
        packages:
          - scanpy
          - scprep
          - sklearn
          - "anndata<0.8"
  - type: nextflow
