name: op3_loader
namespace: datasets/loaders/scrnaseq
description: |
  "Loads and preprocesses the OP3 dataset from GEO accession GSE279945."

argument_groups:
  - name: Input
    arguments:
      - name: "--input"
        type: file
        must_exist: false
        description: "Input h5ad file."
        direction: input
        required: false
        default: ./tmp/GSE279945_sc_counts_processed.h5ad
        example: https://ftp.ncbi.nlm.nih.gov/geo/series/GSE279nnn/GSE279945/suppl/GSE279945_sc_counts_processed.h5ad
      - name: "--var_feature_name"
        type: string
        description: "Location of where to find the feature names. Can be set to index if the feature names are the index."
        default: index
  - name: Data Filtering
    description: "Arguments for filtering the dataset"
    arguments:
      - name: "--donor_id"
        type: string
        description: "Donor ID to filter for (1, 2, or 3). If not specified, all donors are included."
        required: false
      - name: "--cell_type"
        type: string
        description: "Cell type to filter for (T cells, B cells, NK cells, or Myeloid). If not specified, all cell types are included."
        required: false
      - name: "--perturbation"
        type: string
        description: "Perturbation to filter for. If not specified, all perturbations are included."
        required: false

  - name: Dataset Metadata
    description: "Metadata about the dataset"
    arguments:
      - name: "--dataset_id"
        type: string
        description: "Unique identifier for the dataset"
        default: "op3"
      - name: "--dataset_name"
        type: string
        description: "Human-readable name for the dataset"
        default: "OP3: single-cell multimodal dataset in PBMCs for perturbation prediction benchmarking"
      - name: "--dataset_summary"
        type: string
        description: "Short summary of the dataset"
        default: "The Open Problems Perurbation Prediction (OP3) dataset with small molecule perturbations in PBMCs"
      - name: "--dataset_description"
        type: string
        description: "Detailed description of the dataset"
        default: "The OP3 dataset is to-date the largest single-cell small molecule perturbation dataset in primary tissue with multiple donor replicates."
      - name: "dataset_reference"
        type: string
        description: "Bibtex reference of the paper in which the dataset was published."
        required: false
        default: GSE279945
      - name: "--dataset_url"
        type: string
        description: "Link to the original source of the dataset."
        required: false
        default: https://ftp.ncbi.nlm.nih.gov/geo/series/GSE279nnn/GSE279945/suppl/GSE279945_sc_counts_processed.h5ad
          
  - name: Output
    description: "Output parameters"
    arguments:
      - name: "--output"
        type: file
        description: "Output h5ad file."
        direction: output
        required: true
      - name: "--output_compression"
        type: string
        choices: [gzip, lzf]
        required: false
        default: "gzip"

resources:
  - type: python_script
    path: script.py

engines:
  - type: docker
    image: python:3.11
    setup:
      - type: python
        packages:
          - scanpy
          - anndata
          - pandas
          - numpy
          - requests
    test_setup:
      - type: python
        packages:
          - viashpy

runners:
  - type: executable
  - type: nextflow

test_resources:
  - type: python_script
    path: test.py

