__merge__: ../../api/comp_method.yaml

functionality:
  name: seurat
  info:
    label: Seurat
    summary: "Seurat method that is based on Canonical Correlation Analysis (CCA)."
    description: |
      This method applies the 'anchor'-based integration workflow introduced in Seurat v3, that enables the probabilistic transfer of annotations from a reference to a query set. First, mutual nearest neighbors (anchors) are identified from the reference scRNA-seq and query spatial datasets. Then, annotations are transfered from the single cell reference data to the sptial data along with prediction scores for each spot.
    preferred_normalization: counts
    reference: stuart2019comprehensive
    documentation_url: https://satijalab.org/seurat/articles/spatial_vignette
    repository_url: https://github.com/satijalab/seurat

  arguments:
    - name: "--n_pcs"
      type: integer
      default: 30
      description: Number of principal components.
    - name: "--sctransform_n_cells"
      type: integer
      default: 5000
      description: Number of cells sampled to build NB regression.

  resources:
    - type: r_script
      path: script.R

platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_r:1.0.4
    setup:
      - type: r
        cran: [Matrix, Seurat]

  - type: native
  - type: nextflow
    directives:
      label: [midtime, highmem, midcpu]
