__merge__: ../../api/comp_method.yaml
functionality:
  name: saver
  status: disabled
  info:
    label: SAVER
    summary: SAVER (Single-cell Analysis Via Expression Recovery) implements a regularized regression prediction and empirical Bayes method to recover the true gene expression profile.
    description: |
      SAVER takes advantage of gene-to-gene relationships to recover the true expression level of each gene in each cell,
      removing technical variation while retaining biological variation across cells (https://github.com/mohuangx/SAVER).
      SAVER uses a post-quality-control scRNA-seq dataset with UMI counts as input. SAVER assumes that the count of each
      gene in each cell follows a Poisson-gamma mixture, also known as a negative binomial model. Instead of specifying
      the gamma prior, we estimate the prior parameters in an empirical Bayes-like approach with a Poisson LASSO regression,
      using the expression of other genes as predictors. Once the prior parameters are estimated, SAVER outputs the
      posterior distribution of the true expression, which quantifies estimation uncertainty, and the posterior mean is
      used as the SAVER recovered expression value.
    reference: huang2018savergene
    repository_url: https://github.com/mohuangx/SAVER
    documentation_url: https://mohuangx.github.io/SAVER/index.html
    preferred_normalization: counts
  resources:
    - type: r_script
      path: script.R
platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_r:1.0.4
    setup:
      - type: r
        github: mohuangx/SAVER
  - type: nextflow
    directives: 
      label: [midtime, highmem, highcpu]
