__merge__: ../../api/comp_metric.yaml
functionality:
  name: "trustworthiness"
  info:
    metrics:
      - name: trustworthiness
        label: Trustworthiness at k=15
        summary: "A measurement of similarity between the rank of each point's nearest neighbors in the high-dimensional data and the reduced data."
        description: "A measurement of similarity between the rank of each point's nearest neighbors in the high-dimensional data and the reduced data."
        reference: venna2006local
        min: 0
        max: 1
        maximize: true
        v1:
          path: openproblems/tasks/dimensionality_reduction/metrics/trustworthiness.py 
          commit: b3456fd73c04c28516f6df34c57e6e3e8b0dab32
          note: This metric is already included in the 'coranking' component and can be removed.
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.1
    setup:
      - type: python
        packages:
          - scikit-learn
          - numpy
  - type: nextflow
    directives: 
      label: [ midmem, lowcpu ]
