functionality:
  namespace: "match_modalities/methods"
  info:
    type: method
    type_info:
      label: Method
      summary: A multimodal data integration method.
      description: |
        A multimodal method to integrate data.
  arguments:
    - name: "--input_mod1"
      __merge__: file_mod1.yaml
      direction: input
      required: true
    - name: "--input_mod2"
      __merge__: file_mod2.yaml
      direction: input
      required: true
    - name: "--output_mod1"
      __merge__: file_integrated_mod1.yaml
      direction: output
      required: true
    - name: "--output_mod2"
      __merge__: file_integrated_mod2.yaml
      direction: output
      required: true
  test_resources:
    - path: /resources_test/common/scicar_cell_lines
      dest: resources_test/common/scicar_cell_lines
    - type: python_script
      path: /src/common/comp_tests/check_method_config.py
    - type: python_script
      path: /src/common/comp_tests/run_and_check_adata.py
    - path: /src/common/library.bib
    - path: /src/common/api
