functionality:
  name: "process_dataset"
  namespace: "dimensionality_reduction"
  version: "main_build"
  arguments:
  - type: "file"
    name: "--input"
    info:
      label: "Common dataset"
      summary: "A dataset processed by the common dataset processing pipeline."
      description: "This dataset contains both raw counts and normalized data matrices,\n\
        as well as a PCA embedding, HVG selection and a kNN graph."
      slots:
        obsp:
        - type: "double"
          name: "knn_distances"
          description: "K nearest neighbors distance matrix."
          required: true
        - type: "double"
          name: "knn_connectivities"
          description: "K nearest neighbors connectivities matrix."
          required: true
        uns:
        - type: "string"
          name: "dataset_id"
          description: "A unique identifier for the dataset. This is different from\
            \ the `obs.dataset_id` field, which is the identifier for the dataset\
            \ from which the cell data is derived."
          required: true
        - name: "dataset_name"
          type: "string"
          description: "A human-readable name for the dataset."
          required: true
        - type: "string"
          name: "dataset_url"
          description: "Link to the original source of the dataset."
          required: false
        - name: "dataset_reference"
          type: "string"
          description: "Bibtex reference of the paper in which the dataset was published."
          required: false
          multiple: true
        - name: "dataset_summary"
          type: "string"
          description: "Short description of the dataset."
          required: true
        - name: "dataset_description"
          type: "string"
          description: "Long description of the dataset."
          required: true
        - name: "dataset_organism"
          type: "string"
          description: "The organism of the sample in the dataset."
          required: false
          multiple: true
        - type: "string"
          name: "normalization_id"
          description: "Which normalization was used"
          required: true
        - type: "double"
          name: "pca_variance"
          description: "The PCA variance objects."
          required: true
        - type: "object"
          name: "knn"
          description: "Supplementary K nearest neighbors data."
          required: true
        obsm:
        - type: "double"
          name: "X_pca"
          description: "The resulting PCA embedding."
          required: true
        varm:
        - type: "double"
          name: "pca_loadings"
          description: "The PCA loadings matrix."
          required: true
        var:
        - type: "string"
          name: "feature_id"
          description: "Unique identifier for the feature, usually a ENSEMBL gene\
            \ id."
          required: false
        - type: "string"
          name: "feature_name"
          description: "A human-readable name for the feature, usually a gene symbol."
          required: true
        - type: "integer"
          name: "soma_joinid"
          description: "If the dataset was retrieved from CELLxGENE census, this is\
            \ a unique identifier for the feature."
          required: false
        - type: "boolean"
          name: "hvg"
          description: "Whether or not the feature is considered to be a 'highly variable\
            \ gene'"
          required: true
        - type: "double"
          name: "hvg_score"
          description: "A score for the feature indicating how highly variable it\
            \ is."
          required: true
        layers:
        - type: "integer"
          name: "counts"
          description: "Raw counts"
          required: true
        - type: "double"
          name: "normalized"
          description: "Normalised expression values"
          required: true
        obs:
        - type: "string"
          name: "dataset_id"
          description: "Identifier for the dataset from which the cell data is derived,\
            \ useful for tracking and referencing purposes."
          required: false
        - type: "string"
          name: "assay"
          description: "Type of assay used to generate the cell data, indicating the\
            \ methodology or technique employed."
          required: false
        - type: "string"
          name: "assay_ontology_term_id"
          description: "Experimental Factor Ontology (`EFO:`) term identifier for\
            \ the assay, providing a standardized reference to the assay type."
          required: false
        - type: "string"
          name: "cell_type"
          description: "Classification of the cell type based on its characteristics\
            \ and function within the tissue or organism."
          required: false
        - type: "string"
          name: "cell_type_ontology_term_id"
          description: "Cell Ontology (`CL:`) term identifier for the cell type, offering\
            \ a standardized reference to the specific cell classification."
          required: false
        - type: "string"
          name: "development_stage"
          description: "Stage of development of the organism or tissue from which\
            \ the cell is derived, indicating its maturity or developmental phase."
          required: false
        - type: "string"
          name: "development_stage_ontology_term_id"
          description: "Ontology term identifier for the developmental stage, providing\
            \ a standardized reference to the organism's developmental phase.\n\n\
            If the organism is human (`organism_ontology_term_id == 'NCBITaxon:9606'`),\
            \ then the Human Developmental Stages (`HsapDv:`) ontology is used.  \n\
            If the organism is mouse (`organism_ontology_term_id == 'NCBITaxon:10090'`),\
            \ then the Mouse Developmental Stages (`MmusDv:`) ontology is used.\n\
            Otherwise, the Uberon (`UBERON:`) ontology is used.\n"
          required: false
        - type: "string"
          name: "disease"
          description: "Information on any disease or pathological condition associated\
            \ with the cell or donor."
          required: false
        - type: "string"
          name: "disease_ontology_term_id"
          description: "Ontology term identifier for the disease, enabling standardized\
            \ disease classification and referencing.\n\nMust be a term from the Mondo\
            \ Disease Ontology (`MONDO:`) ontology term, or `PATO:0000461` from the\
            \ Phenotype And Trait Ontology (`PATO:`).\n"
          required: false
        - type: "string"
          name: "donor_id"
          description: "Identifier for the donor from whom the cell sample is obtained."
          required: false
        - type: "boolean"
          name: "is_primary_data"
          description: "Indicates whether the data is primary (directly obtained from\
            \ experiments) or has been computationally derived from other primary\
            \ data."
          required: false
        - type: "string"
          name: "organism"
          description: "Organism from which the cell sample is obtained."
          required: false
        - type: "string"
          name: "organism_ontology_term_id"
          description: "Ontology term identifier for the organism, providing a standardized\
            \ reference for the organism.\n\nMust be a term from the NCBI Taxonomy\
            \ Ontology (`NCBITaxon:`) which is a child of `NCBITaxon:33208`.\n"
          required: false
        - type: "string"
          name: "self_reported_ethnicity"
          description: "Ethnicity of the donor as self-reported, relevant for studies\
            \ considering genetic diversity and population-specific traits."
          required: false
        - type: "string"
          name: "self_reported_ethnicity_ontology_term_id"
          description: "Ontology term identifier for the self-reported ethnicity,\
            \ providing a standardized reference for ethnic classifications.\n\nIf\
            \ the organism is human (`organism_ontology_term_id == 'NCBITaxon:9606'`),\
            \ then the Human Ancestry Ontology (`HANCESTRO:`) is used.\n"
          required: false
        - type: "string"
          name: "sex"
          description: "Biological sex of the donor or source organism, crucial for\
            \ studies involving sex-specific traits or conditions."
          required: false
        - type: "string"
          name: "sex_ontology_term_id"
          description: "Ontology term identifier for the biological sex, ensuring\
            \ standardized classification of sex. Only `PATO:0000383`, `PATO:0000384`\
            \ and `PATO:0001340` are allowed."
          required: false
        - type: "string"
          name: "suspension_type"
          description: "Type of suspension or medium in which the cells were stored\
            \ or processed, important for understanding cell handling and conditions."
          required: false
        - type: "string"
          name: "tissue"
          description: "Specific tissue from which the cells were derived, key for\
            \ context and specificity in cell studies."
          required: false
        - type: "string"
          name: "tissue_ontology_term_id"
          description: "Ontology term identifier for the tissue, providing a standardized\
            \ reference for the tissue type.\n\nFor organoid or tissue samples, the\
            \ Uber-anatomy ontology (`UBERON:`) is used. The term ids must be a child\
            \ term of `UBERON:0001062` (anatomical entity).\nFor cell cultures, the\
            \ Cell Ontology (`CL:`) is used. The term ids cannot be `CL:0000255`,\
            \ `CL:0000257` or `CL:0000548`.\n"
          required: false
        - type: "string"
          name: "tissue_general"
          description: "General category or classification of the tissue, useful for\
            \ broader grouping and comparison of cell data."
          required: false
        - type: "string"
          name: "tissue_general_ontology_term_id"
          description: "Ontology term identifier for the general tissue category,\
            \ aiding in standardizing and grouping tissue types.\n\nFor organoid or\
            \ tissue samples, the Uber-anatomy ontology (`UBERON:`) is used. The term\
            \ ids must be a child term of `UBERON:0001062` (anatomical entity).\n\
            For cell cultures, the Cell Ontology (`CL:`) is used. The term ids cannot\
            \ be `CL:0000255`, `CL:0000257` or `CL:0000548`.\n"
          required: false
        - type: "string"
          name: "batch"
          description: "A batch identifier. This label is very context-dependent and\
            \ may be a combination of the tissue, assay, donor, etc."
          required: false
        - type: "integer"
          name: "soma_joinid"
          description: "If the dataset was retrieved from CELLxGENE census, this is\
            \ a unique identifier for the cell."
          required: false
        - type: "double"
          name: "size_factors"
          description: "The size factors created by the normalisation method, if any."
          required: false
    example:
    - "resources_test/common/pancreas/dataset.h5ad"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--output_dataset"
    info:
      label: "Dataset"
      summary: "The dataset to pass to a method."
      slots:
        layers:
        - type: "integer"
          name: "counts"
          description: "Raw counts"
          required: true
        - type: "double"
          name: "normalized"
          description: "Normalized expression values"
          required: true
        var:
        - type: "double"
          name: "hvg_score"
          description: "High variability gene score (normalized dispersion). The greater,\
            \ the more variable."
          required: true
        uns:
        - type: "string"
          name: "dataset_id"
          description: "A unique identifier for the dataset"
          required: true
        - type: "string"
          name: "normalization_id"
          description: "Which normalization was used"
          required: true
    example:
    - "resources_test/dimensionality_reduction/pancreas/dataset.h5ad"
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--output_solution"
    info:
      label: "Test data"
      summary: "The data for evaluating a dimensionality reduction."
      slots:
        layers:
        - type: "integer"
          name: "counts"
          description: "Raw counts"
          required: true
        - type: "double"
          name: "normalized"
          description: "Normalized expression values"
          required: true
        obs:
        - type: "string"
          name: "cell_type"
          description: "Classification of the cell type based on its characteristics\
            \ and function within the tissue or organism."
          required: true
        var:
        - type: "double"
          name: "hvg_score"
          description: "High variability gene score (normalized dispersion). The greater,\
            \ the more variable."
          required: true
        uns:
        - type: "string"
          name: "dataset_id"
          description: "A unique identifier for the dataset"
          required: true
        - name: "dataset_name"
          type: "string"
          description: "Nicely formatted name."
          required: true
        - type: "string"
          name: "dataset_url"
          description: "Link to the original source of the dataset."
          required: false
        - name: "dataset_reference"
          type: "string"
          description: "Bibtex reference of the paper in which the dataset was published."
          required: false
        - name: "dataset_summary"
          type: "string"
          description: "Short description of the dataset."
          required: true
        - name: "dataset_description"
          type: "string"
          description: "Long description of the dataset."
          required: true
        - name: "dataset_organism"
          type: "string"
          description: "The organism of the sample in the dataset."
          required: false
        - type: "string"
          name: "normalization_id"
          description: "Which normalization was used"
          required: true
    example:
    - "resources_test/dimensionality_reduction/pancreas/solution.h5ad"
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  resources:
  - type: "python_script"
    path: "script.py"
    is_executable: true
  - type: "file"
    path: "src/common/helper_functions/subset_anndata.py"
  test_resources:
  - type: "file"
    path: "resources_test/common/pancreas/"
    dest: "resources_test/common/pancreas/"
  - type: "python_script"
    path: "src/common/comp_tests/run_and_check_adata.py"
    is_executable: true
  info:
    type: "process_dataset"
    type_info:
      label: "Data processor"
      summary: "A dimensionality reduction dataset processor."
      description: "A component for processing a Common Dataset into a task-specific\
        \ dataset.\n"
  status: "enabled"
  set_wd_to_resources_dir: false
platforms:
- type: "docker"
  id: "docker"
  image: "openproblems/base_python:1.0.0"
  target_organization: "openproblems-bio/openproblems"
  target_registry: "ghcr.io"
  namespace_separator: "/"
  resolve_volume: "Automatic"
  chown: true
  setup_strategy: "ifneedbepullelsecachedbuild"
  target_image_source: "https://github.com/openproblems-bio/openproblems"
  entrypoint: []
  cmd: null
- type: "nextflow"
  id: "nextflow"
  directives:
    label:
    - "midtime"
    - "highmem"
    - "highcpu"
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      lowmem: "memory = 20.Gb"
      midmem: "memory = 50.Gb"
      highmem: "memory = 100.Gb"
      lowcpu: "cpus = 5"
      midcpu: "cpus = 15"
      highcpu: "cpus = 30"
      lowtime: "time = 1.h"
      midtime: "time = 4.h"
      hightime: "time = 8.h"
      veryhightime: "time = 24.h"
    script:
    - "process.errorStrategy = 'ignore'"
  debug: false
  container: "docker"
info:
  config: "/home/runner/work/openproblems/openproblems/src/tasks/dimensionality_reduction/process_dataset/config.vsh.yaml"
  platform: "docker"
  output: "/home/runner/work/openproblems/openproblems/target/docker/dimensionality_reduction/process_dataset"
  executable: "/home/runner/work/openproblems/openproblems/target/docker/dimensionality_reduction/process_dataset/process_dataset"
  viash_version: "0.8.6"
  git_commit: "e354e53a769af0c4ae1ac947a5d240115af0b5bb"
  git_remote: "https://github.com/openproblems-bio/openproblems"
