__merge__: ../../api/comp_control_method.yaml

functionality:
  name: random_proportions
  info:
    label: Random Proportions
    summary: "Negative control method that randomly assigns celltype proportions from a Dirichlet distribution."
    description: |
      A negative control method with random assignment of predicted celltype proportions from a Dirichlet distribution.
    preferred_normalization: counts

  resources:
    - type: python_script
      path: script.py

platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.4
    setup:
      - type: python
        packages: numpy
  - type: native
  - type: nextflow
    directives:
      label: [midtime, midmem, midcpu]
