# use metric api spec
__merge__: ../../api/comp_metric_embedding.yaml
functionality:
  name: asw_batch
  description: Average silhouette of batches per label
  info:
    v1_url: openproblems/tasks/_batch_integration/batch_integration_embed/metrics/sil_batch.py
    v1_commit: 29803b95c88b4ec5921df2eec7111fd5d1a95daf
    paper_reference: luecken2022benchmarking
    metrics:
      - metric_id: asw_batch
        metric_name: ASW batch
        min: 0
        max: 1
        maximize: true
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: mumichae/scib-base:1.0.2
    setup:
      - type: python
        pypi: 
          - pyyaml
  - type: nextflow
