__merge__: ../../api/comp_metric.yaml
functionality:
  name: "accuracy"
  info:
    v1_url: openproblems/tasks/label_projection/metrics/accuracy.py
    v1_commit: fcd5b876e7d0667da73a2858bc27c40224e19f65
    metrics:
      - name: accuracy
        pretty_name: Accuracy
        summary: "The percentage of correctly predicted labels."
        description: "The percentage of correctly predicted labels."
        reference: ""
        repository_url: ""
        documentation_url: ""
        min: 0
        max: 1
        maximize: true
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base-python:latest
    setup:
      - type: python
        packages: scikit-learn
  - type: nextflow
