# use method api spec
__merge__: ../../api/comp_method_feature.yaml
functionality:
  name: combat
  namespace: batch_integration/methods_feature
  description: "Adjusting batch effects in microarray expression data using
    empirical Bayes methods"
  info:
    type: method
    method_name: Combat
    paper_reference: "hansen2012removing"
    code_url: https://scanpy.readthedocs.io/en/stable/api/scanpy.pp.combat.html
    v1_url: openproblems/tasks/_batch_integration/batch_integration_graph/methods/combat.py
    v1_commit: 29803b95c88b4ec5921df2eec7111fd5d1a95daf
    preferred_normalization: log_cpm
    variants:
      combat_full_unscaled:
      combat_hvg_unscaled:
        hvg: true
      combat_full_scaled:
        preferred_normalization: log_cpm_scaled
      combat_hvg_scaled:
        hvg: true
        preferred_normalization: log_cpm_scaled
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: mumichae/scib-base:1.0.2
    setup:
      - type: python
        pypi: 
          - pyyaml
  - type: nextflow
