__inherits__: ../../api/comp_normalization.yaml
functionality:
  name: "normalize_log_scran_pooling"
  namespace: "label_projection/data_processing"
  description: "Normalize data"
  resources:
    - type: r_script
      path: script.R
platforms:
  - type: docker
    image: eddelbuettel/r2u:22.04
    setup:
      - type: r
        cran: [ Matrix, scran, BiocParallel, rlang, anndata]
      - type: apt
        packages: [ libhdf5-dev, libgeos-dev, python3, python3-pip, python3-dev, python-is-python3 ]
      - type: python
        pip: [anndata<0.8, scanpy]
  - type: nextflow
