functionality:
  name: "download"
  namespace: "common/dataset_loader"
  version: "dev"
  description: "Download a dataset."
  authors:
    - name: "Michaela Mueller"
      roles: [ maintainer, author ]
      props: { github: mumichae }
  arguments:
    - name: "--url"
      type: "string"
      description: "URL of dataset"
      required: true
    - name: "--name"
      type: "string"
      example: "pbmc"
      description: "Name of dataset"
      required: true
    - name: "--obs_celltype"
      type: "string"
      description: "Location of where to find the observation cell types."
    - name: "--obs_batch"
      type: "string"
      description: "Location of where to find the observation batch IDs."
    - name: "--obs_tissue"
      type: "string"
      description: "Location of where to find the observation tissue information."
    - name: "--output"
      alternatives: ["-o"]
      type: "file"
      direction: "output"
      example: "output.h5ad"
      description: "Output h5ad file of the cleaned dataset"
      required: true
      info:
        slots:
          X: 
            type: integer
            name: counts
            description: Raw counts
            required: true
          obs:
            - type: string
              name: celltype
              description: Cell type labels
              required: false
            - type: string
              name: batch
              description: Batch information
              required: false
            - type: string
              name: tissue
              description: Tissue information
              required: false
          uns:
            - type: string
              name: dataset_id
              description: "A unique identifier for the dataset"
              required: false
            - type: string
              name: raw_dataset_id
              description: "A unique identifier for the original dataset (before preprocessing)"
              required: false
  resources:
    - type: python_script
      path: script.py
  test_resources:
    - type: python_script
      path: test.py
platforms:
  - type: docker
    image: "python:3.8"
    setup:
      - type: python
        packages:
          - scanpy
          - "anndata<0.8"
  - type: nextflow
