functionality:
  name: "scanvi_all_genes"
  namespace: "label_projection/methods/scvi"
  version: "dev"
  description: "Probabilistic harmonization and annotation of single-cell transcriptomics data with deep generative models."
  authors:
    - name: "Scott Gigante"
      roles: [ author ]
      props: { github: scottgigante }
    - name: "Vinicius Chagas"
      roles: [ maintainer ]
      props: { github: chagasVinicius }
  arguments:
    - name: "--input"
      alternatives: ["-i"]
      type: "file"
      example: "input.h5ad"
      description: "Input file that will be used to generate predictions"
      required: true
    - name: "--n_hidden"
      type: "integer"
      required: true
      default: "10"
    - name: "--n_layers"
      type: "integer"
      required: true
      default: "1"
    - name: "--n_latent"
      type: "integer"
      required: true
      default: "10"
    - name: "--max_epochs"
      type: "integer"
      required: false
    - name: "--limit_brain_batches"
      type: "integer"
      required: false
    - name: "--limit_val_batches"
      type: "integer"
      required: false
    - name: "--output"
      alternatives: ["-o"]
      type: "file"
      direction: "output"
      example: "output.h5ad"
      description: "Output data labeled"
      required: true
  resources:
    - type: python_script
      path: script.py
    - path: "../tools.py"
  tests:
    - type: python_script
      path: test_script.py
    - type: file
      path: "../../../resources/pancreas/toy_preprocessed_data.h5ad"
platforms:
  - type: docker
    image: "python:3.8"
    setup:
      - type: python
        packages:
          - scanpy
          - scprep
          - sklearn
          - "anndata<0.8"
          - scvi-tools
  - type: native
  - type: nextflow
