__merge__: ../../api/comp_control_method.yaml
functionality:
  name: "random_features"
  namespace: "dimensionality_reduction/control_methods"
  description: "Negative control method which generates a random embedding "
  info:
    type: negative_control
    label: Random features
    v1_url: openproblems/tasks/dimensionality_reduction/methods/baseline.py
    v1_commit: b460ecb183328c857cbbf653488f522a4034a61c
    preferred_normalization: counts
  resources:
    - type: python_script
      path: script.py
  test_resources:
    - type: python_script
      path: test.py
    - path: ../../../../resources_test/common/pancreas/
      dest: input
platforms:
  - type: docker
    image: "python:3.10"
    setup:
      - type: python
        packages:
          - numpy
          - "anndata>=0.8"
          - pyyaml
  - type: nextflow