__merge__: ../../api/comp_method.yaml
functionality:
  name: "magic"
  info:
    label: MAGIC
    summary: "MAGIC imputes and denoises scRNA-seq data using Euclidean distances and a Gaussian kernel to calculate the affinity matrix, followed by a Markov process and multiplication with the normalised data to obtain imputed values."
    description: "MAGIC (Markov Affinity-based Graph Imputation of Cells) is a method for
        imputation and denoising of noisy or dropout-prone single cell RNA-sequencing
        data. Given a normalised scRNA-seq expression matrix, it first calculates
        Euclidean distances between each pair of cells in the dataset, which is then
        augmented using a Gaussian kernel (function) and row-normalised to give a
        normalised affinity matrix. A t-step markov process is then calculated, by
        powering this affinity matrix t times. Finally, the powered affinity matrix
        is right-multiplied by the normalised data, causing the final imputed values
        to take the value of a per-gene average weighted by the affinities of cells.
        The resultant imputed matrix is then rescaled, to more closely match the
        magnitude of measurements in the normalised (input) matrix."
    reference: "van2018recovering"
    documentation_url: "https://github.com/KrishnaswamyLab/MAGIC#readme"
    repository_url: "https://github.com/KrishnaswamyLab/MAGIC"
    v1:
      path: openproblems/tasks/denoising/methods/magic.py
      commit: 29803b95c88b4ec5921df2eec7111fd5d1a95daf
    variants: 
      magic:
      magic_approx:
        solver: approximate
      knn_naive:
        norm: log
        decay: none
        t: 1
    preferred_normalization: counts
  arguments:
    - name: "--solver"
      type: "string"
      choices: ["exact", "approximate"]
      default: "exact"
      description: Which solver to use.
    - name: "--norm"
      type: string
      choices: ["sqrt", "log"]
      default: "sqrt"
      description: Normalization method
    - name: "--decay"
      type: integer
      default: 1
      description: sets decay rate of kernel tails
    - name: "--t"
      type: integer
      default: 3
      description: power to which the diffusion operator is powered
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.1
    setup:
      - type: python
        pip: [scprep, magic-impute, scipy, scikit-learn<1.2]
  - type: nextflow
    directives: 
      label: [ highmem, highcpu ]
