# use method api spec
__merge__: ../../api/comp_control_method_embedding.yaml
functionality:
  name: random_embed_cell
  info:
    label: Random Embedding by Celltype
    summary: "Cells are embedded as a one-hot encoding of celltype labels"
    description: "Cells are embedded as a one-hot encoding of celltype labels"
    v1:
      path: openproblems/tasks/_batch_integration/batch_integration_embed/methods/baseline.py
      commit: b3456fd73c04c28516f6df34c57e6e3e8b0dab32
    preferred_normalization: log_cpm
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.0
    setup:
      - type: python
        pypi:
          - scikit-learn
  - type: nextflow
