__merge__: ../../api/comp_metric.yaml
functionality:
  name: mse
  info:
    metrics:
      - name: rmse
        label: RMSE
        summary: The root mean squared error.
        description: The square root of the mean of the square of all of the error.
        min: 0
        max: "+inf"
        maximize: false
        reference: chai2014root
      - name: mae
        label: MAE
        summary: The mean absolute error.
        description: The average difference between the expression values and the predicted expression values.
        min: 0
        max: "+inf"
        maximize: false
        reference: chai2014root
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.1
  - type: nextflow
    directives:
      label: [ lowmem, lowcpu ]
