functionality:
  namespace: "predict_modality/control_methods"
  info:
    type: control_method
    preferred_normalization: counts # there is currently only one type of normalization
    type_info:
      label: Control method
      summary: Quality control methods for verifying the pipeline.
      description: |
        These components have the same interface as the regular methods
        but also receive the solution object as input. It serves as a
        starting point to test the relative accuracy of new methods in
        the task, and also as a quality control for the metrics defined
        in the task. 
  arguments:
    - name: "--input_train_mod1"
      __merge__: file_train_mod1.yaml
      direction: input
      required: true
    - name: "--input_train_mod2"
      __merge__: file_train_mod2.yaml
      direction: input
      required: true
    - name: "--input_test_mod1"
      __merge__: file_test_mod1.yaml
      direction: input
      required: true
    - name: "--input_test_mod2"
      __merge__: file_test_mod2.yaml
      direction: input
      required: true
    - name: "--output"
      __merge__: file_prediction.yaml
      direction: output
      required: true
  test_resources:
    - type: python_script
      path: /src/common/comp_tests/check_method_config.py
    - type: python_script
      path: /src/common/comp_tests/run_and_check_adata.py
    - path: /resources_test/predict_modality/openproblems_neurips2021/bmmc_cite_GEX2ADT
      dest: resources_test/predict_modality/openproblems_neurips2021/bmmc_cite_GEX2ADT