type: file
example: "resources_test/predict_modality/openproblems_neurips2021/bmmc_cite/swap/train_mod2.h5ad"
info:
  label: "Train mod2"
  summary: "The mod2 expression values of the train cells."
  slots:
    layers:
      - type: integer
        name: counts
        description: Raw counts
        required: true
      - type: double
        name: normalized
        description: Normalized expression values
        required: true
    obs:
      - type: string
        name: batch
        description: Batch information
        required: true
      - type: double
        name: size_factors
        description: The size factors of the cells prior to normalization.
        required: false
    var:
      - type: string
        name: gene_ids
        description: The gene identifiers (if available)
        required: false
    uns:
      - type: string
        name: dataset_id
        description: "A unique identifier for the dataset"
        required: true
      - type: string
        name: common_dataset_id
        description: "A common identifier for the dataset"
        required: false
      - name: dataset_organism
        type: string
        description: The organism of the sample in the dataset.
        required: false
      - name: normalization_id
        type: string
        description: The unique identifier of the normalization method used.
        required: true
      - type: string
        name: gene_activity_var_names
        description: "Names of the gene activity matrix"
        required: false
    obsm:
      - type: double
        name: gene_activity
        description: ATAC gene activity
        required: false