type: file
example: "resources_test/common/openproblems_neurips2021/bmmc_cite/dataset_mod1.h5ad"
info:
  label: "Raw dataset RNA"
  summary: "The RNA modality of the raw dataset."
  slots:
    layers:
      - type: integer
        name: counts
        description: Raw counts
        required: true
      - type: double
        name: normalized
        description: Normalized expression values
        required: true
    obs:
      - type: string
        name: batch
        description: Batch information
        required: true
      - type: double
        name: size_factors
        description: The size factors of the cells prior to normalization.
        required: false
    var:
      - type: string
        name: feature_id
        description: Unique identifier for the feature, usually a ENSEMBL gene id.
        # TODO: make this required once openproblems_v1 dataloader supports it
        required: true
      
      - type: string
        name: feature_name
        description: A human-readable name for the feature, usually a gene symbol.
        # TODO: make this required once the dataloader supports it
        required: true
    uns:
      - type: string
        name: dataset_id
        description: "A unique identifier for the dataset"
        required: true
      - name: dataset_name
        type: string
        description: Nicely formatted name.
        required: true
      - type: string
        name: dataset_url
        description: Link to the original source of the dataset.
        required: false
      - name: dataset_reference
        type: string
        description: Bibtex reference of the paper in which the dataset was published.
        required: false
      - name: dataset_summary
        type: string
        description: Short description of the dataset.
        required: true
      - name: dataset_description
        type: string
        description: Long description of the dataset.
        required: true
      - name: dataset_organism
        type: string
        description: The organism of the sample in the dataset.
        required: false
      - type: string
        name: gene_activity_var_names
        description: "Names of the gene activity matrix"
        required: false
    obsm:
      - type: double
        name: gene_activity
        description: ATAC gene activity
        required: false