__merge__: ../../api/comp_normalization.yaml
functionality:
  name: "l1_sqrt"
  description: |
    Scaled L1 sqrt normalization.

    This normalization method causes all cells to have the same sum of values.

    Steps:

    * Compute the square root of the counts.
    * Apply L1 normalization (rescaled such that the sum of the values of each cell sum to 1).
    * Multiply by the median UMI count per cell, causing all cells to have the sum of values.
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.1
    setup:
      - type: python
        packages:
          - scprep
          - numpy
  - type: nextflow
    directives: 
      label: [ "midtime", lowmem, lowcpu ]
