# use metric api spec
__merge__: ../../api/comp_metric_feature.yaml
functionality:
  name: hvg_overlap
  info:
    metrics:
      - name: hvg_overlap
        label: HVG overlap
        summary: Overlap of highly variable genes per batch before and after integration.
        description: |
          The HVG conservation score is a proxy for the preservation of
          the biological signal. If the data integration method returned
          a corrected data matrix, we computed the number of HVGs before
          and after correction for each batch via Scanpyâ€™s
          highly_variable_genes function (using the â€˜cell rangerâ€™ flavor).
          If available, we computed 500 HVGs per batch. If fewer than 500
          genes were present in the integrated object for a batch,
          the number of HVGs was set to half the total genes in that batch.
          The overlap coefficient is as follows:
          overlap(ğ‘‹,ğ‘Œ)=|ğ‘‹âˆ©ğ‘Œ|/min(|ğ‘‹|,|ğ‘Œ|),

          where X and Y denote the fraction of preserved informative genes.
          The overall HVG score is the mean of the per-batch HVG overlap
          coefficients.
        reference: luecken2022benchmarking
        min: 0
        max: 1
        maximize: true
        v1:
          path: openproblems/tasks/_batch_integration/batch_integration_feature/metrics/hvg_conservation.py
          commit: b3456fd73c04c28516f6df34c57e6e3e8b0dab32
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.4
    setup:
      - type: python
        pypi:
          - scib==1.1.5
  - type: nextflow
    directives: 
      label: [midtime, midmem, lowcpu]
