functionality:
  name: process_openproblems_v1
  namespace: datasets/workflows
  description: |
    Fetch and process legacy OpenProblems v1 datasets
  argument_groups:
    - name: Inputs
      arguments:
        - name: "--id"
          type: string
          description: Unique identifier of the dataset.
          required: true
        - name: "--input_id"
          type: "string"
          description: "The ID of the dataset in OpenProblems v1"
          required: true
        - name: "--obs_cell_type"
          type: "string"
          description: "Location of where to find the observation cell types."
        - name: "--obs_batch"
          type: "string"
          description: "Location of where to find the observation batch IDs."
        - name: "--obs_tissue"
          type: "string"
          description: "Location of where to find the observation tissue information."
        - name: "--layer_counts"
          type: "string"
          description: "In which layer to find the counts matrix. Leave undefined to use `.X`."
          example: counts
        - name: "--sparse"
          type: boolean
          default: true
          description: Convert layers to a sparse CSR format.
    - name: Metadata
      arguments:
        - name: "--dataset_name"
          type: string
          description: Nicely formatted name.
          required: true
        - name: "--dataset_url"
          type: string
          description: Link to the original source of the dataset.
          required: false
        - name: "--dataset_reference"
          type: string
          description: Bibtex reference of the paper in which the dataset was published.
          required: false
        - name: "--dataset_summary"
          type: string
          description: Short description of the dataset.
          required: true
        - name: "--dataset_description"
          type: string
          description: Long description of the dataset.
          required: true
        - name: "--dataset_organism"
          type: string
          description: The organism of the dataset.
          required: false
    - name: Sampling options
      arguments:
        - name: "--do_subsample"
          type: boolean
          default: false
          description: "Whether or not to subsample the dataset"
        - name: "--n_obs"
          type: integer
          description: Maximum number of observations to be kept. It might end up being less because empty cells / genes are removed.
          default: 500
        - name: "--n_vars"
          type: integer
          description: Maximum number of variables to be kept. It might end up being less because empty cells / genes are removed.
          default: 500
        - name: "--keep_features"
          type: string
          multiple: true
          description: A list of genes to keep.
        - name: "--keep_cell_type_categories"
          type: "string"
          multiple: true
          description: "Categories indexes to be selected"
          required: false
        - name: "--keep_batch_categories"
          type: "string"
          multiple: true
          description: "Categories indexes to be selected"
          required: false
        - name: "--even"
          type: "boolean_true"
          description: Subsample evenly from different batches
        - name: "--seed"
          type: "integer"
          description: "A seed for the subsampling."
          example: 123
    - name: Normalization
      arguments:
        - name: "--normalization_methods"
          type: string
          multiple: true
          choices: ["log_cp10k", "log_cpm", "sqrt_cp10k", "sqrt_cpm", "l1_sqrt", "log_scran_pooling"]
          default: ["log_cp10k", "log_cpm", "sqrt_cp10k", "sqrt_cpm", "l1_sqrt"]
          description: "Which normalization methods to run."
    - name: Outputs
      arguments:
        - name: "--output_dataset"
          __merge__: /src/datasets/api/file_common_dataset.yaml
          direction: "output"
          required: true
        - name: "--output_meta"
          direction: "output"
          type: file
          description: "Dataset metadata"
          default: "dataset_metadata.yaml"
        - name: "--output_raw"
          __merge__: /src/datasets/api/file_raw.yaml
          direction: "output"
          required: false
        - name: "--output_normalized"
          __merge__: /src/datasets/api/file_normalized.yaml
          direction: "output"
          required: false
        - name: "--output_pca"
          __merge__: /src/datasets/api/file_pca.yaml
          direction: "output"
          required: false
        - name: "--output_hvg"
          __merge__: /src/datasets/api/file_hvg.yaml
          direction: "output"
          required: false
        - name: "--output_knn"
          __merge__: /src/datasets/api/file_knn.yaml
          direction: "output"
          required: false
  resources:
    - type: nextflow_script
      path: main.nf
      entrypoint: run_wf
    - path: /src/wf_utils/helper.nf
  dependencies: 
    - name: datasets/loaders/openproblems_v1
    - name: datasets/normalization/log_cp
    - name: datasets/normalization/log_scran_pooling
    - name: datasets/normalization/sqrt_cp
    - name: datasets/normalization/l1_sqrt
    - name: datasets/processors/subsample
    - name: datasets/processors/pca
    - name: datasets/processors/hvg
    - name: datasets/processors/knn
    - name: common/extract_metadata
  # test_resources:
  #   - type: nextflow_script
  #     path: main.nf
  #     entrypoint: test_wf
platforms:
  - type: nextflow
