# use method api spec
__merge__: ../../api/comp_method_embedding.yaml
functionality:
  name: scvi
  description: Run scVI on adata object
  info:
    pretty_name: scVI
    summary: "scVI combines a variational autoencoder with a hierarchical Bayesian model."
    description: |
      scVI combines a variational autoencoder with a hierarchical Bayesian model. It uses the negative binomial distribution to describe gene expression of each cell, conditioned on unobserved factors and the batch variable. ScVI is run as implemented in Luecken et al.
    reference: "lopez2018deep"
    repository_url: "https://github.com/YosefLab/scvi-tools"
    documentation_url: "https://github.com/YosefLab/scvi-tools#readme"
    v1_url: openproblems/tasks/_batch_integration/batch_integration_graph/methods/scvi.py
    v1_commit: 29803b95c88b4ec5921df2eec7111fd5d1a95daf
    preferred_normalization: log_cpm
    variants:
      scvi_full_unscaled:
      scvi_hvg_unscaled:
        hvg: true
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: mumichae/scib-base:1.1.3
    setup:
      - type: python
        pypi:
          - scvi-tools
          - pyyaml
  - type: nextflow
