__merge__: ../../api/comp_method_feature.yaml
functionality:
  name: scalex_feature
  info:
    label: SCALEX (feature)
    summary: Online single-cell data integration through projecting heterogeneous datasets into a common cell-embedding space
    description : |
      SCALEX is a method for integrating heterogeneous single-cell data online using a VAE framework. Its generalised encoder disentangles batch-related components from batch-invariant biological components, which are then projected into a common cell-embedding space.
    reference: xiong2021online
    repository_url: https://github.com/jsxlei/SCALEX
    documentation_url: https://scalex.readthedocs.io
    v1:
      path: openproblems/tasks/_batch_integration/batch_integration_graph/methods/scalex.py
      commit: b3456fd73c04c28516f6df34c57e6e3e8b0dab32
    preferred_normalization: log_cp10k
    variants:
      scalex_feature_unscaled:
      scanorama_feature_scaled:
        preferred_normalization: log_cp10k_scaled
  arguments:
    - name: --n_hvg
      type: integer
      default: 2000
      description: Number of highly variable genes to use.
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.4
    setup:
      - type: python
        pypi:
          - scalex
          - numpy<1.24
          - torch<2.1
  - type: nextflow
    directives:
      label: [lowmem, lowcpu, midtime]
