name: integration test

on: workflow_dispatch

jobs:
  # phase 1
  list_components:
    env:
      s3_bucket: s3://openproblems-data/resources_test/
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Fetch viash
      run: |
        bin/init
        bin/viash -h

    # create cachehash key
    - name: Create hash key
      id: cachehash
      run: |
        AWS_EC2_METADATA_DISABLED=true aws s3 ls $s3_bucket --recursive --no-sign-request > bucket-contents.txt
        echo "cachehash=resources_test__$( md5sum bucket-contents.txt | awk '{ print $1 }' )" >> $GITHUB_OUTPUT
    
    # initialize cache
    - name: Cache resources data
      uses: actions/cache@v3
      with:
        path: resources_test
        key: ${{ steps.cachehash.outputs.cachehash }}
        restore-keys: resources_test_

    # sync if need be
    - name: Sync test resources
      run: |
        bin/viash run \
          -p native \
          src/common/sync_test_resources/config.vsh.yaml -- \
          --input $s3_bucket \
          --delete
        tree resources_test/ -L 3

    - name: Build target dir
      run: |
        # allow publishing the target folder
        sed -i '/^target.*/d' .gitignore

        # build target dir
        bin/viash ns build --config_mod ".functionality.version := 'integration_build'" --parallel  --setup donothing

    - name: Deploy to target branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
        publish_branch: integration_build

    # store component locations
    - id: set_matrix
      run: |
        component_json=$(bin/viash ns list -p docker --format json | jq -c '[ .[] |  { "name": .functionality.name, "config": .info.config } ]')
        echo "component_matrix=$component_json" >> $GITHUB_OUTPUT
        workflow_json=$(bin/viash ns list -s workflows --format json | jq -c '[ .[] | { "name": .functionality.name, "config": .info.config, "test_script": .functionality.test_resources[].path, "entry": .functionality.test_resources[].entrypoint } ]')
        echo "workflow_matrix=$workflow_json" >> $GITHUB_OUTPUT
    outputs:
      component_matrix: ${{ steps.set_matrix.outputs.component_matrix }}
      workflow_matrix: ${{ steps.set_matrix.outputs.workflow_matrix }}
      cachehash: ${{ steps.cachehash.outputs.cachehash }}

  # phase 2
  build_containers:
    needs: list_components

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        component: ${{ fromJson(needs.list_components.outputs.component_matrix) }}

    steps:
    - uses: actions/checkout@v3

    - name: Fetch viash
      run: |
        bin/init
        bin/viash -h

    - name: Build container
      run: |
        SRC_DIR=`dirname ${{ matrix.component.config }}`
        bin/viash ns build --config_mod ".functionality.version := 'integration_build'" -s "$SRC_DIR" --setup build
        
    - name: Login to container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.GTHB_USER }}
        password: ${{ secrets.GTHB_PAT }}

    - name: Push containers
      run: |
        SRC_DIR=`dirname ${{ matrix.component.config }}`
        bin/viash ns build --config_mod ".functionality.version := 'integration_build'" -s "$SRC_DIR" --setup donothing --push

  ###################################
  # phase 3
  integration_test:
    needs: [ build_containers, list_components ]

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        component: ${{ fromJson(needs.list_components.outputs.workflow_matrix) }}

    steps:
    - uses: actions/checkout@v3

    - name: Fetch viash
      run: |
        bin/init
        bin/viash -h

    # build target dir
    # use containers from integration_build branch, hopefully these are available
    - name: Build target dir
      run: |
        # build target dir
        bin/viash ns build --config_mod ".functionality.version := 'integration_build'" --parallel  --setup donothing

    # use cache
    - name: Cache resources data
      uses: actions/cache@v3
      timeout-minutes: 5
      with:
        path: resources_test
        key: ${{ needs.list_components.outputs.cachehash }}

    - name: Run integration test
      timeout-minutes: 45
      run: |
        # todo: replace with viash test command
        config_dir=`dirname ${{ matrix.component.config }}`
        script="$config_dir/${{ matrix.component.test_script }}"
        export NXF_VER=22.04.5
        bin/nextflow run . \
          -main-script "$script" \
          -entry ${{ matrix.component.entry }} \
          -profile docker,mount_temp,no_publish \
          -c workflows/utils/labels_ci.config
