name: main build

on:
  push:
    branches: [ 'main' ]

jobs:
  # phase 1
  list:
    runs-on: ubuntu-latest

    outputs:
      component_matrix: ${{ steps.set_matrix.outputs.matrix }}
      cache_key: ${{ steps.cache.outputs.cache_key }}

    steps:
    - uses: actions/checkout@v3

    - uses: viash-io/viash-actions/setup@v2

    - name: Remove target folder from .gitignore
      run: |
        # allow publishing the target folder
        sed -i '/^target.*/d' .gitignore

    - uses: viash-io/viash-actions/ns-build@v2
      with:
        config_mod: .functionality.version := 'main_build'
        parallel: true

    - name: Build nextflow schemas
      uses: viash-io/viash-actions/build-nextflow-schemas@v2
      with:
        workflows: workflows
        components: src
        token: ${{ secrets.GTHB_PAT }}
        tools_version: 'main_build'
   
    - name: Build parameter files
      uses: viash-io/viash-actions/build-nextflow-params@v2
      with:
        workflows: workflows
        components: src
        token: ${{ secrets.GTHB_PAT }}
        tools_version: 'main_build'

    - name: Deploy to target branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
        publish_branch: main_build

    - id: ns_list
      uses: viash-io/viash-actions/ns-list@v2
      with:
        platform: docker
        src: src
        format: json

    - id: set_matrix
      run: |
        echo "matrix=$(jq -c '[ .[] | 
          { 
            "name": (.functionality.namespace + "/" + .functionality.name),
            "dir": .info.config | capture("^(?<dir>.*\/)").dir
          }
        ]' ${{ steps.ns_list.outputs.output_file }} )" >> $GITHUB_OUTPUT

  # phase 2
  build:
    needs: list

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        component: ${{ fromJson(needs.list.outputs.component_matrix) }}

    steps:
    - uses: actions/checkout@v3

    - uses: viash-io/viash-actions/setup@v2

    - name: Build container
      uses: viash-io/viash-actions/ns-build@v2
      with:
        config_mod: .functionality.version := 'main_build'
        platform: docker
        src: ${{ matrix.component.dir }}
        setup: build
        
    - name: Login to container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.GTHB_USER }}
        password: ${{ secrets.GTHB_PAT }}

    - name: Push container
      uses: viash-io/viash-actions/ns-build@v2
      with:
        config_mod: .functionality.version := 'main_build'
        platform: docker
        src: ${{ matrix.component.dir }}
        setup: push