functionality:
  name: transform_meta
  namespace: common/workflows
  description: >-
    This workflow transforms the meta information of the results into a format
    that can be used by the website.
  argument_groups:
    - name: Inputs
      arguments:
        - name: "--input_scores"
          type: file
          required: true
          direction: input
          description: A yaml file containing the scores of each of the methods
          example: score_uns.yaml
        - name: "--input_method_configs"
          type: file
          required: true
          direction: input
          example: method_configs.yaml
        - name: "--input_metric_configs"
          type: file
          required: true
          direction: input
          example: metric_configs.yaml
        - name: "--input_dataset_info"
          type: file
          required: true
          direction: input
          example: dataset_info.yaml
        - name: "--input_execution"
          type: file
          required: true
          direction: input
          example: trace.txt
        - name: "--input_task_info"
          type: file
          required: true
          direction: input
          example: task_info.yaml
        - name: "--task_id"
          type: string
          required: true
          direction: input
          example: "batch_integration"
    - name: Outputs
      arguments:
        - name: "--output_scores"
          type: file
          required: true
          direction: output
          description: A yaml file containing the scores of each of the methods
          example: results.json
        - name: "--output_method_info"
          type: file
          required: true
          direction: output
          example: method_info.json
        - name: "--output_metric_info"
          type: file
          required: true
          direction: output
          example: metric_info.json
        - name: "--output_dataset_info"
          type: file
          required: true
          direction: output
          example: dataset_info.json
        - name: "--output_task_info"
          type: file
          required: true
          direction: output
          example: task_info.json
  resources:
    - type: nextflow_script
      path: main.nf
      entrypoint: run_wf
  dependencies:
    - name: common/get_results
    - name: common/get_method_info
    - name: common/get_metric_info
    - name: common/yaml_to_json
platforms:
  - type: nextflow