__merge__: ../../api/comp_control_method.yaml
functionality:
  name: "true_features"
  namespace: "dimensionality_reduction/control_methods"
  description: "Positive control method which generates high-dimensional (full data) embedding"
  info:
    type: positive_control
    label: True Features
    paper_name: "True Features (baseline)"
    paper_url: "https://openproblems.bio"
    paper_year: 2022
    code_url: "https://github.com/openproblems-bio/openproblems"
    v1_url: openproblems/tasks/dimensionality_reduction/methods/baseline.py
    v1_commit: 4a0ee9b3731ff10d8cd2e584726a61b502aef613
    preferred_normalization: counts
  arguments:
    - name: "--n_comps"
      type: integer
      default: 100
      description: Number of principal components to use.
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: "python:3.10"
    setup:
      - type: python
        packages:
          - scanpy
          - "anndata>=0.8"
          - pyyaml
  - type: nextflow
    directives: 
      label: [ highmem, highcpu ]
