__merge__: ../../api/comp_method.yaml
functionality:
  name: "pca"
  namespace: "dimensionality_reduction/methods"
  description: "Principal component analysis (PCA)"
  info:
    method_name: "PCA"
    paper_reference: pearson1901pca
    code_url: https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.PCA.html
    v1_url: openproblems/tasks/dimensionality_reduction/methods/pca.py
    v1_commit: 14d70b330cae09527a6d4c4e552db240601e31cf
    preferred_normalization: log_cpm
    variants:
      pca_logCPM:
      pca_logCPM_1kHVG:
        n_hvg: 1000
  arguments:
    - name: "--n_hvg"
      type: integer
      description: Number of highly variable genes to subset to. If not specified, the input matrix will not be subset.
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: "python:3.10"
    setup:
      - type: python
        packages:
          - scanpy
          - "anndata>=0.8"
  - type: nextflow
    directives: 
      label: [ highmem, highcpu ]
