__merge__: ../../api/comp_method.yaml
functionality:
  name: "pca"
  namespace: "dimensionality_reduction/methods"
  info:
    pretty_name: "PCA"
    summary: "A linear method that finds orthogonal directions to compute the two-dimensional embedding, capturing maximum variance from logCPM expression matrix with/without selecting 1000 HVGs."
    description: |
      'Principal Component Analysis is a linear method that finds orthogonal
      directions in the data that capture the most variance. The first two
      principal components are chosen as the two-dimensional embedding. We select
      only the first two principal components as the two-dimensional embedding. PCA
      is calculated on the logCPM expression matrix with and without selecting 1000
      HVGs.' 
    reference: pearson1901pca
    repository_url: "https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.PCA.html"
    documentatoin_url: "https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.PCA.html"
    v1_url: openproblems/tasks/dimensionality_reduction/methods/pca.py
    v1_commit: 14d70b330cae09527a6d4c4e552db240601e31cf
    preferred_normalization: log_cpm
    variants:
      pca_logCPM:
      pca_logCPM_1kHVG:
        n_hvg: 1000
  arguments:
    - name: "--n_hvg"
      type: integer
      description: Number of highly variable genes to subset to. If not specified, the input matrix will not be subset.
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: "python:3.10"
    setup:
      - type: python
        packages:
          - scanpy
          - pyyaml
          - "anndata>=0.8"
  - type: nextflow
    directives: 
      label: [ highmem, highcpu ]
