__merge__: ../../api/comp_method.yaml
functionality:
  name: "pca"
  namespace: "dimensionality_reduction/methods"
  description: "Principal component analysis"
  info:
    type: method
    label: PCA
    v1_url: openproblems/tasks/dimensionality_reduction/methods/pca.py
    v1_commit: a796e02e13a43e8861b124edbb9d287f162d4a14
    preferred_normalization: log_cpm
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: "python:3.10"
    setup:
      - type: python
        packages:
          - scanpy
          - "anndata>=0.8"
          - pyyaml
  - type: nextflow